### ISSUE TITLE
Server-Generated Connection ID should include a cryptographic MAC

### ISSUE THREAD

**Issue by ThomasSwindells** [quicwg/ops-drafts#11]
The guidance recommend that server generated connection IDs should include a crytographic MAC when being used for load balancing. This sounds like a good suggestion in principal, but the Connection ID is 64bits in size, I'm not a cryptographer but I don't see how this is possible - if it is possible then it perhaps would be good to include guidance within the documents?

My logic is as follows (hopefully I've made a mistake/misunderstood the concept somewhere)

As a CDN operator I'd probably want to segment the connection ID into 4 spaces:
POP id|machine id|unique connection|MAC

You could combine your POP id and machine ID into a single space but it is likely to be beneficial to have two tiers, the POP routes the request to the right general location and the machine id then identifies a machine within that space. Other ways to split this are also possible.

If 12 bits are used for POP id that would give 4096 distinct locations. Trends to deploy deeper into networks (particularly within mobile/cell base stations) doesn't make this number totally infeasible .
If 8 bits are then used for a machine id within a POP that gives 256 possible machines. 

This means 20 bits might be used for load balancing purposes. This gives a bit (lot?) of room for flexibility and it is unlikely all million combinations are used but it is probably the right order of magnitude for a large widely distributed CDN (even if we drop down to 16 bits it doesn't significantly impact the analysis below).

The actual unique connection pool needs to be large enough to avoid repeating too quickly - even if you have a lot of clients taking advantage of 0RTT to aggressively close/re-open connections. There also presumably needs to be some randomization of the ids so that they aren't created sequentially. I've assumed 24 bits (which is only 16 million unique ids per server).

This only leaves 20 bits left for the MAC, that is about 1 million possible values. As I've said I'm not a cryptographer but to me this looks small enough that a brute force attack guided by some valid inputs might be feasible even on relatively low power machines? 

For that matter isn't a simple replay attack feasible? The MAC can't be based upon the full 5-tuple as we need to support connection mobility. You could embed a timestamp into the id somewhere to protect against this but that would use up even more bits, otherwise you could slowly gather up valid (but presumably closed) connection ids and then aggressively replay them all in a short time period.

**Comment by igorlord** [comment]
> This only leaves 20 bits left for the MAC, that is about 1 million possible values. As I've said I'm not a cryptographer but to me this looks small enough that a brute force attack guided by some valid inputs might be feasible even on relatively low power machines?

The goal of the MAC is not make a brute force attacker unable to generate a "valid" Connection ID but to make it a relatively low-probability event.  The only reason I see to have a MAC at all is to make it harder for an attacker to mount an effective attack on a single backend using your routing infrastructure for steering.  QUIC as a protocol is resilient to man-on-a-side attack vector (except during handshake), so attackers guessing valid connection IDs is not a big deal.

The key is to have enough entropy ("unique connection" size) so you do not accidentally create duplicate connection IDs.

**Comment by mirjak** [comment]
Closed now. Please send PR if you think more text is needed.
