### ISSUE TITLE
connection migration: add server preferred address

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#115]
We should probably make it clear what the application can do here (SPA for servers; maybe intentional migration for clients?) I'm not sure if migration is transparent to client applications or not.

**Comment by mirjak** [comment]
The client application might have some knowledge if it's behind a NAT or not and as such might want to indicate to use Conn ID or not. We can make that more explicit in the text.

**Comment by mirjak** [comment]
I did some small edits on the text in the connection migration section but @martinduke maybe you had something more in mind and want to propose more text?

**Comment by mirjak** [comment]
This whole section should then also be moved to after the Conn ID section.

**Comment by martinduke** [comment]
I like the move of text to the manageability draft. If it were me, I'd move "Server-Generated Connection ID" as well, as I don't think apps need to worry about it, but it's not a big deal.

I think adding text about server preferred address is probably more important for this draft.

**Comment by mirjak** [comment]
Added some more text in #127

**Comment by britram** [comment]
@martinduke we think the current state of the draft addresses this issue; could you check and close this issue if so?
