### ISSUE TITLE
Does connection ID stuff belong in applicability draft?

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#116]
Is this something application designers need to think about or manage? I would hope QUIC implementations would handle this transparently.

To the extent you have to configure something like QUIC-LB, that's a manageability thing.

**Comment by britram** [comment]
Connection IDs are weird, in that they are important to both implementors / deployers (so applicability) as opposed to operators of networks that are not necessarily at the endpoints (so manageability)

**Comment by mirjak** [comment]
There is text about Connection ID in both documents. We can double-check though that the text is well aligned and splitter correctly.

**Comment by martinduke** [comment]
Well, implementors are explicitly out of scope according to the document's introduction. I would hope that apps didn't have to worry about Connection ID properties very much, or at all.

Maybe there is knob or two for information exposure, at most, but I'd consider most of this text to be extraneous to the applicabilty draft.

**Comment by mirjak** [comment]
I think we actually put some text in the wrong doc. PR #121 moves this text from applicability to manageability.
