### ISSUE TITLE
Advise against short idle timeouts?

### ISSUE THREAD

**Issue by britram** [quicwg/ops-drafts#118]
in #102, @pravb said:

> One concern I have with short idle timeout is impact on VM live migration. The current guidance with TCP default timeouts allows LM to have a blackout period of under 9 seconds. Do we need any guidance here to not use very low default timeouts?

This probably needs its own discussion...

**Comment by britram** [comment]
note that we use the words "idle timeout" two different ways in the applicability document:

(1) the network idle timeout, which is the shortest state timeout of a device on a path between the endpoints
(2) the endpoint idle timeout transport parameter, which is the point at which a connection will simply silently close.

While addressing this question (which I interpret as "we present session resumption as a solution for clients, but what about servers?), we should also clear up the terminology.

**Comment by britram** [comment]
Setting a QUIC endpoint idle timeout above 30 sec won't have much effect here because of the prevalence of 30s UDP network idle timeouts on middleboxes. So guidance here should max out at 30s.

Given the variety of different ways VM live migration is implemented and the variety of network control planes that can be used to steer traffic in this situation, the guidance should also not be too low... so if there is guidance here I'd say it should be in the 10-30s range. @pravb does this seem reasonable?

**Comment by britram** [comment]
See also / reference RFC 4787 (for UDP) and RFC 7857 / 2663 (for TCP).

**Comment by ianswett** [comment]
I'd suggest a min of 30 seconds as being sensible for the public internet, and longer may be preferable if the deployment can consistently survive NAT rebinds.

We have applications with much longer(ie: 5 minute) timeouts in production, but they don't do hanging GETs and our infrastructure is designed to correctly handle NAT rebinds.

**Comment by mirjak** [comment]
addressed by #125
