### ISSUE TITLE
CI appears broken

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#130]
Maybe try GitHub Actions.

```sh
git -C lib fetch origin
git -C lib checkout main
cp -R lib/template/.github .
git add .github
git commit
```

**Comment by britram** [comment]
CircleCI is actually building the docs (and submits on pushed annotated tags), but I also just noticed that ghpages is somehow desynced.

The suggestion above would move to GitHub Actions; I presume I'd need to turn CircleCI off as well...

**Comment by martinthomson** [comment]
Yes, turning off Circle would help avoid having them fight each other.

**Comment by britram** [comment]
hm, the master/main switch seems to be confounding me here:

```
➜  quic-ops-master git:(master) git -C lib fetch origin 
remote: Enumerating objects: 453, done.
remote: Counting objects: 100% (448/448), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 391 (delta 230), reused 358 (delta 199), pack-reused 0
Receiving objects: 100% (391/391), 49.96 KiB | 655.00 KiB/s, done.
Resolving deltas: 100% (230/230), completed with 41 local objects.
From https://github.com/martinthomson/i-d-template
 * [new tag]         v1         -> v1
➜  quic-ops-master git:(master) git -C lib fetch origin main
From https://github.com/martinthomson/i-d-template
 * branch            main       -> FETCH_HEAD
➜  quic-ops-master git:(master) git -C lib checkout main    
error: pathspec 'main' did not match any file(s) known to git
```

**Comment by martinthomson** [comment]
```
git -C lib checkout main FETCH_HEAD
```

Perhaps?

`git reset` might need to be involved.

**Comment by britram** [comment]
there's also this: 

```
lib/id.mk:3: *************************************************
lib/id.mk:4: ***                                           ***
lib/id.mk:5: ***   You are using the 'master' branch.      ***
lib/id.mk:6: ***   Please update to use 'main'.            ***
lib/id.mk:7: ***                                           ***
lib/id.mk:8: ***   sed -i~ s/master/main/ Makefile         ***
lib/id.mk:9: ***                                           ***
lib/id.mk:10: *************************************************
```

**Comment by martinthomson** [comment]
That smells like you need to do something drastic.

```
rm -rf lib
git clone https://github.com/martinthomson/i-d-template lib
```

**Comment by britram** [comment]
yeah I've done an appropriate amount of blasting things away and I've got a PR incoming...

**Comment by britram** [comment]
one cannot ask for a more direct verification that a PR has the intended effect :)

![github_circle_ci](https://user-images.githubusercontent.com/1884116/99494748-d6fed400-2971-11eb-99a1-4c6841c1d57a.png)

**Comment by britram** [comment]
Hi Lars, I need an admin to click Stop Building [here](https://app.circleci.com/settings/project/github/quicwg/ops-drafts?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fquicwg%2Fops-drafts) to finish migrating off CircleCI; is that you?

**Comment by britram** [comment]
(There might also be settings on the GitHub repository side that would disable this, but the UI has changed since the last time I did this and I... can't find them, if I'm authorized to use them)

**Comment by larseggert** [comment]
That link isn't loading for me? Can't you simply remove the circleCI (and Travis) config files?

**Comment by larseggert** [comment]
OK, the link started working after I logged in separately. Clicked!

**Comment by britram** [comment]
oh wow there was still a travis file. removed that too.

Thanks, Lars, this looks good to me now (and thanks @martinthomson for making HG actions migration so easy after I un-Gitted my repo).
