### ISSUE TITLE
2^62-1 is a harder limit than implied

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#136]
>  In the presently unlikely event that this limit is reached by an application, the stream can simply be closed and replaced with a new one.

This text in [Section 4](https://quicwg.org/ops-drafts/draft-ietf-quic-applicability.html#section-4-2) is incorrect.  When you have sent that much data, the connection flow control limit cannot be increased further.  Consequently, though many additional streams can be opened when a stream hits this limit, you cannot send any bytes on any of those streams.

I recommend striking this sentence or replacing it with a note about this fundamental limit applying to all data conveyed in streams.

**Comment by mirjak** [comment]
Happy to take a PR :-)
