### ISSUE TITLE
You can't close stream ingress

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#137]
> However, an endpoint can abruptly close either the ingress or egress direction; these actions are fully independent of each other.

This text in [Section 4](https://quicwg.org/ops-drafts/draft-ietf-quic-applicability.html#section-4-3) is incorrect.  An endpoint can abruptly close (reset) egress data, but it can only *request* that its peer abruptly close ingress (using STOP_SENDING).

**Comment by mirjak** [comment]
is there a missing "not"? Do you mean: s/An endpoint can abruptly close (reset) egress data/An endpoint cannot abruptly close (reset) egress data/ ?

Anyway, yes, we need to fix that!
