### ISSUE TITLE
Critical streams aren't worth a whole paragraph

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#138]
I think that the text on [streams that are critical to an application](https://quicwg.org/ops-drafts/draft-ietf-quic-applicability.html#section-4-4) can be removed.

This was an interesting discussion in HTTP/3, but I'm not sure that the applicability statement needs to concern itself with this detail.

**Comment by mirjak** [comment]
The intention was, given it was an interesting discussion in H3, it might worth mentioning as other application may have the same "problem". I think it doesn't hurt to keep it. Or is there any concern that the term "critical stream" is maybe not well enough defined?
