### ISSUE TITLE
Normative language in applicability statement

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#139]
There are a few instances that might be read as normative statements.  Is that really wise?

Examples:

> applications should not assume access to these identifiers

cannot?

> fallback MUST not silently violate the application's expectation of confidentiality or integrity of its payload data

Maybe this isn't something that this document needs to say.  It could just say that fallback to unencrypted TCP might not be a desirable outcome.

There is also a bunch of "MUST"-level statements in the 0-RTT section, but I've proposed a rewrite that (I hope) eliminates them.

**Comment by britram** [comment]
Fixed in #132: removed all 2119 language.
