### ISSUE TITLE
Integrity Protection is not quite right

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#142]
In manageability:

"Integrity Protection of the Wire Image {#wire-integrity}
As soon as the cryptographic context is established, all information in the QUIC header, including information exposed in the packet header, is integrity protected. Further, information that was sent and exposed in handshake packets sent before the cryptographic context was established are validated later during the cryptographic handshake. Therefore, devices on path cannot alter any information or bits in QUIC packet headers, since alteration of header information will lead to a failed integrity check at the receiver, and can even lead to connection termination."

This isn't precise. The Initial packet is not meaningfully integrity-protected, but the contents of the CRYPTO frame (and the connection IDs) are. An on-path attacker could, for instance, change the ClientHello's Packet Number to from '0' to '1' and then adjust the ACK frame from '1' to '0'. (Why would one do this?)

**Comment by mirjak** [comment]
Is the ACK frame in the case not encrypted...?

**Comment by martinduke** [comment]
The Initial is decryptable by anyone, and so could be rewritten.

**Comment by mirjak** [comment]
Okay. What do we want to right here now?

**Comment by martinduke** [comment]
how about "...cannot alter any information or bits in QUIC packet headers, since alteration..." changing to:

"...cannot alter any information or bits in QUIC packet headers, except specific parts of Initial packets, since alteration..."

**Comment by mirjak** [comment]
WFM. I can change that as soon as your PR landed (or you add it to your PR).
