### ISSUE TITLE
Do clients really use zero-length CIDs?

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#143]
"Connection ID and rebinding"
"typically, however, only the server will request a connection ID for the lifetime of the connection."

While I totally accept that this would be reasonable in the real world, is this remotely true about existing client implementations? I admit to not checking recently, but I suspect client CIDs are predominant.

**Comment by nibanks** [comment]
For what it's worth, MsQuic uses zero-length CIDs on the client by default. Only when explicitly sharing the local UDP port does it use CIDs to differentiate between the different connections.

**Comment by martinthomson** [comment]
We plan to use zero-length connection IDs.  At least initially.  There are use cases where we would want to use a different strategy.

**Comment by ianswett** [comment]
Chrome/Cronet also use zero-length CIDs and have for years.  I don't see any motivation to change this anytime soon in those clients.

**Comment by martinduke** [comment]
Closed, as I am obviously misinformed as to what clients are doing.
