### ISSUE TITLE
Does the length self-encoding scheme actually work?

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#144]
In "Connection ID and Rebinding":

"Even when encrypted, a scheme could embed the unencrypted length of the Connection ID in the Connection ID itself, instead of remembering it, e.g. by using the first few bits to indicate a certain size of a well-known set of possible sizes with multiple values that indicate the same size but are selected randomly."

I almost went and filed an issue against quic-lb to do this instead of just encoding a plaintext length like it does currently. But is this a good recommended practice? ISTM that long headers would provide a bit of a Rosetta Stone for this mapping, making it not particularly effective for the complexity.

**Comment by mirjak** [comment]
The idea was not to conceal the length but to avoid likability by identifying linked connection based on the existence of a certain length field. This might look slightly more random but I guess you also have to change your mapping more time to time. So not sure. I'm fine to remove that half sentence and maybe add a sentence about likability instead...?

**Comment by martinduke** [comment]
Yes, I would prefer deleting the quoted text, as I think it's a solution that adds complexity for little apparent benefit.

**Comment by mirjak** [comment]
Okay, will do that change after your PR has landed.
