### ISSUE TITLE
DDoS guidance is inaccurate about QUIC-LB

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#147]
"QUIC's linkability resistance ensures that a deliberate connection migration is accompanied by a change in the connection ID and necessitate that connection ID aware DDoS defense system must have the same information about connection IDs as the load balancer {{?I-D.ietf-quic-load-balancers}}. This may be complicated where mitigation and load balancing environments are logically separate."

This is insufficient. Even the load balancer is only able to identify the end server, not the connection.

**Comment by martinduke** [comment]
On a related note, the suggestion to use the "first 8 bytes" of a server's connection ID is somewhat strange. Why not observe the CIDL it's using in long headers, or just have common configuration?

**Comment by mirjak** [comment]
How about if we just remove any wording about load balancers here? Like this maybe:

```
QUIC's linkability resistance ensures that a deliberate connection migration is accompanied by a change in the connection ID and necessitate that DDoS defense system are connection ID aware.
```

**Comment by mirjak** [comment]
On the 8 bytes: I actually not sure where this comes from, however, I assume that the thinking was that using the first 8 bytes might be good enough to avoid collisions if you don't know the connection ID length. But I guess we can remove it or add some more explanation... any thoughts?

**Comment by martinduke** [comment]
If you read the Retry Services section of QUIC-LB, you'll see that there is no dependence on the Connection ID encoding at all. It is a common format for Retry Tokens that allows servers to (at a minimum) extract the original CIDs necessary for verification.

Certainly, no device should drop packets simply because the CID has changed, which is maybe what you're trying to say here? But I'm not sure that this is a DDoS thing.

**Comment by mirjak** [comment]
The point is when a DDoS attack is on-going you want to make sure that on-going connections keep running while new connections are handled more carefully. So you have to be flow aware. However, maybe it's acceptable if connectivity breaks during a DDoS when the 5 tuple changes...? Otherwise you would need to be CID aware.
