### ISSUE TITLE
Should DDoS section talk about Retry Services?

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#148]
I am not really sure at all that the existing DDoS guidance is good advice; we have a somewhat more robust plan in quic-lb, which perhaps we should reference?

**Comment by martinduke** [comment]
for that matter, the Retry packet does not make an appearance in this section at all, which seems like an oversight.

**Comment by mirjak** [comment]
Yes to both. Can you provide an PR?

**Comment by martinduke** [comment]
Yes, please assign this issue to me.
