### ISSUE TITLE
Explain emulation of partial reliability with one message per stream?

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#15]

**Comment by ianswett** [comment]
I think explaining how reset can create partial reliability would be useful.  I think that's orthogonal to whether it's a bidirectional stream model or a message model, though.  One could use partial reliability in both cases.

**Comment by britram** [comment]
Phrased as guidance on the use of resetting streams, this is useful. I don't think we're blocking on this, though, and in any case I wouldn't want whatever advice we give here to conflict with whatever partial reliability approach ends up in V2.

**Comment by britram** [comment]
Discussion in BKK seems to have converged on "don't do this for v1 applicability statement; applicability of PR and different PR strategies belongs in a document discussing PR as an extension". closing for now.

**Comment by britram** [comment]
oops, going to leave this open to track discussion. note that #54 covers an alternate view of this.

**Comment by britram** [comment]
there's a line of text in the working copy on this now: "If one message is
mapped on a single stream, resetting the stream if the message is not needed
anymore can be used to emulate partial reliability on a message basis." This is probably sufficient.
