### ISSUE TITLE
Connection ID linkability is missing a premise

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#151]
[Mitigating Timing Linkability with Connection ID Migration](https://quicwg.org/ops-drafts/draft-ietf-quic-applicability.html#name-mitigating-timing-linkabili) launches right into discussion of how linkability protections might be inadequate without really establishing what the requirements are or why they exist.  This needs an introduction paragraph.

**Comment by mirjak** [comment]
Note sure how much more we want to say here or can say at this point in time....

@martinthomson if you have a more concrete idea what we should say here, can you give it a try and propose a PR?

**Comment by martinthomson** [comment]
Something like:

> QUIC requires that endpoints generate fresh connection IDs for use on new network paths.  Choosing values that are unlinkable to an outside observer ensures that activity on different paths cannot be trivially correlated using the connection ID.

Then launch into the existing discussion.

**Comment by mirjak** [comment]
Sounds good to me. I can add that after you PR landed or you can add it to your PR.
