### ISSUE TITLE
Does TCP fallback require TLS 1.3?

### ISSUE THREAD

**Issue by LPardue** [quicwg/ops-drafts#174]
Applicability section 2 says:

```
All applications running on top of QUIC must therefore either be prepared to accept connectivity failure on such networks, or be engineered to fall back to some other transport protocol. In the case of HTTP, this fallback is TLS 1.3 over TCP.
```

I'm not sure how practical this advice is. Requiring a fallback to TLS 1.3 specifically seems problematic due to the diversity of HTTP versions and TLS versions that are deployed today. (NB: I agree with a general raising of the bar for security, but I don't think this document is the place to state it)

We can assume that any HTTP version might learn about HTTP/3 via Alt-Svc or HTTPSVC. This could for example be HTTP/1.1 over TCP port 80. Such a client could fallback to the version it learned about QUIC from, and nothing bad would happen.

**Comment by mirjak** [comment]
This wasn't meant to enforce any restriction. The assumption was simply that if you have implemented QUIC, you might have probably also implemented TLS1.3... however, I guess we can just remove the "1.3" here and only say "TLS over TCP". Okay?

**Comment by ianswett** [comment]
One could argue it should require TLS 1.3, since otherwise there's an easy security downgrade, but I'm not sure that's something we could require.

**Comment by LPardue** [comment]
IMO we need to accommodate disparate support across versions. To give an example, a CDN operator may have QUIC and HTTP endpoints that are configured differently according to customer configuration. With QUIC v1 it is safe to assume only TLS 1.3 so a CDN might not provide configuration for TLS version. However, other HTTP versions could theoretically be configured only to support a maximum of TLS 1.2. Since plaintext HTTP and TLS 1.2 are not prohibited for use on the internet, it seems odd to levy a requirement that prevents them being used in one specific chain of interactions. 

Mirja's suggestion to say "TLS over TCP" is better but would still not address the plaintext HTTP case. A user agent might see http://example.com, connect to port 80, and get Alt-Svc'd to HTTP/3. If the something goes wrong and TLS is not permitted, then all connectivity might be broken forever.

**Comment by mirjak** [comment]
In the same section later we say 

```
Any fallback mechanism is likely to impose a degradation of performance; however, fallback must not silently violate the application's expectation of confidentiality or integrity of its payload data.
```

I hope that addresses your point about security downgrade, @ianswett ?

**Comment by ianswett** [comment]
It might be worth saying "likely to impose a degradation on performance and can degrade security;"?

**Comment by mirjak** [comment]
I created a PR and also changed the order of sentences a bit to make the it more clear.

@LPardue is there anything else you think we need to say here?
