### ISSUE TITLE
Discuss application-layer graceful/scheduled close

### ISSUE THREAD

**Issue by LPardue** [quicwg/ops-drafts#175]
https://quicwg.org/ops-drafts/draft-ietf-quic-applicability.html#section-8 deals with connection closure and is pretty exhaustive. However, I think it would be improved by discussing how an application protocol might manage graceful connection close in the absence of a transport-layer mechanism. HTTP/3 defines the GOAWAY frame for this purpose, defining the closure signalling mechnanism and the  behaviour of endpoints when in the draining period - especially wrt creating streams.

**Comment by mirjak** [comment]
@LPardue would you be able to propose some text?

**Comment by LPardue** [comment]
I'll try 😀

**Comment by mirjak** [comment]
#298 is merged
