### ISSUE TITLE
Sect 2.4: MTU or Min QUIC Packet Size?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#177]
Sect 2.4: says:  “the network path meets minimum Maximum Transmission Unit (MTU) requirements. “ There is text in the QUIC transport spec that the WG perfected a little in the final stages, and I think this use of MTU in sect 2.3  is suspect. As I see it, the requirements in QUIC are for a minimum supported QUIC packet size... not the MTU required to send this on an interface. 
... This nuanced might be a really important detail for operations staff - where there is frequently a need to consider encapsulations and tunnels on interfaces of devices.
... A cross reference to the QUIC Spec may also help here.

**Comment by mirjak** [comment]
@gorryfair can you propose text?

**Comment by gorryfair** [comment]
Thought to be addressed in PR #262

**Comment by mirjak** [comment]
PR #262 merged
