### ISSUE TITLE
Sect 2.7: Telling middleboxes to ignore version?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#178]
Sect 2.7 contains a specific statement as a recommendations for middleboxes. At the moment this is buried within a section on version negotiation. The present text says:
“In addition, due to the speed of evolution of the protocol, devices that attempt to distinguish QUIC traffic from non- QUIC traffic for purposes of network admission control should admit all QUIC traffic regardless of version.”

I think I understand the intent, and see the encouragement, but I really do not all buy this as a generic "recommendation". I think this topic that can be tricky for network ops people (e.g. protecting enterprise access). I've raised this a number of times in previous face-to-face IETF discussions.  There are good reasons why DDoS and other devices will have a policy that is based on a set of signatures that identify behaviours the administrators trust and for which they have appropriate management procedures.  Please can we adjust this as a motivation for allowing easy upgrade, rather than  boldly saying “should admit”.

It might also be good for this change in thinking to be more highlighted, and the editors might want to call out the importance of thinking about the implications, In this respect I'd encourage this to be a separate subsection.

**Comment by mirjak** [comment]
@gorry there wasn't much discussion here yet, however when we say we might need a separate section to discussion this more differentiated, what would/should that section say? Can you maybe even propose text?

**Comment by mirjak** [comment]
Ted said during the ietf-110 meeting in the chat: For #178, maybe it is "Treat all QUIC traffic equally, without regard to version"?

**Comment by mirjak** [comment]
@gorry can we close this or can you propose concrete changes?

**Comment by britram** [comment]
@gorryfair we'll go ahead and close this; please reopen if you have a text proposal. thanks!
