### ISSUE TITLE
Sect 4.6: emphatically NOT RECOMMENDED use of ACK mitigation?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#182]
The text says: “and are emphatically NOT RECOMMENDED.” I think I would agree with a strong encouragement to not do this, but I would suggest to not use upper case letters at this point, and I’m not sure “emphatically” is a great word in a RFC :-).

I’d also note that the volume of ACK traffic really can be a problem that QUIC needs to address, because QUIC over radio (of various types) can be significantly more expensive or lower performant than TCP, precisely because the control/ACK traffic is much more and there is no opportunity for network mitigation - hence it behoves QUIC implementors to use appropriate methods.

**Comment by mirjak** [comment]
I created an PR to address the first point.

Regarding the second point: @gorryfair do you want to propose additional text? However, if I think that would go the into applicability...?

**Comment by gorryfair** [comment]
Suggestion for text:
   On network paths where there is significant asymmetry,
   the transmission of QUIC ACKs can reduce the efficient use of network 
   capacity or transmission opportunities.  This effect occurs
   when the return capacity is significantly more constrained than the
   forward capacity, or the cost of transmission per packet is a
   significant component of the total transmission cost.  Reducing
   the ratio of acknowledgements to data at the QUIC receiver can improve
   link utilization and reduce link transmission costs.
