### ISSUE TITLE
This issue contains a set of editorial NiTs from QUIC Manageability-09

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#185]
This section contains a series, of assumed editorial comments. (The issue is copied from the QUIC WG list).
“Even thought this bit is fixed in the QUICv1 specification,”
-  This seems like the wrong word: /thought/though/
---
“observers cannot reliably use“
-Maybe we could avoid “reliably”, e.g.:
 /cannot depend on this bit as/...
---
“first octet in the short packet header.”
would probably benefit from an indication of bit ordering and cross-reference to the QUIC spec.
---
Sect 2.4: “In the nominal case” - this use of “nominal” was unusual to me, the word is used differently in different English-speaking regions - in some it might mean “marginal” or only correct at the current time - in other regions it might mean something else. Is “normal” acceptable in this sentence?
---
Section 2.3: “We therefore consider” - who is the “we”, suggest something like “These are considered...”
---
“in the clear” - would be simpler as “without encryption” or “observable on-path”?
---
The term “exposes” is used several times, without saying to whom, which I think in the context of this document, could be clearer as “exposes this, making it visible to an on-path observer”. Also this form of wording is consistent with sect 2.7. This also could help explain this in a more positive light to someone wishing to manage a network.
---
Sect 2.4: “The amount of 0-RTT protected data is limited by the initial congestion window, typically around 10 packets [RFC6928].”
- I suggest this should instead be reference to a section in the QUIC spec. (This does in turn point to 6928, but I think the dependency here is on what QUIC says.)
---
Sect 2.8”: ...”any manipulation of ... will be detected”
I think the word “manipulation” hints like it is illicit, can we use neutral language by saying something like “any change by network devices on-path”?
---
Sect 3.1: “First, it only provides one bit of information and is quite prone to collide with UDP-based protocols other than those that this static bit is meant to allow multiplexing with.“
This seems to lack a little polish (“quite prone”, “meant to ...with”).
---
Sect 3.3.1.
/through passive measurement/by observation by an on-path observer/
... I think this applies, whether it is measurement, filtering, whatever, so we could use the same term.
---
/which each one byte of zeros/ ... seems an odd set of words to me.
---
Section 4.1: “Keying state off the connection ID may therefore cause undetectable and unrecoverable loss of state in the middle of a connection.  Use of connection ID specifically discouraged for NAT applications.”
... I didn’t find /Keying state/ very helpful... maybe some other words would be clearer. The second sentence seems to miss /is/?
---
Sect 4.6: “ Distinguishing ACK packets is trivial in TCP,“
- well, this is not really trivial, because there are pure ACKs and data+ACK which makes this complicated. RFC3449 says more.
---

**Comment by larseggert** [comment]
@gorryfair thank you **very** much for opening individual issues! Just checking that this issue here is supposed to be a meta-issue to track the individual other ones you opened?

**Comment by gorryfair** [comment]
This one is a bunch of editorial NiTs. The editors might like to scan these and check if these are purely text comments they can correct. If there are specifics they wish to pull-out as issues as more than simple text changes, I'd expect this to be closed and they can make separate issues for those that require discussion.

**Comment by britram** [comment]
All suggestions except the following accepted without comment; many thanks for the detailed review!

- I'm going to consider _The term “exposes” is used several times, without saying to whom_  as a stylistic suggestion, and decline to address. I don't think there's a better way to say this without making the flow much more awkward. Please reopen this issue after closure if you disagree strongly.

**Comment by gorryfair** [comment]
Thanks Brian 

> On 12 Feb 2021, at 18:29, Brian Trammell <notifications@github.com> wrote:
> 
> ﻿
> All suggestions except the following accepted without comment; many thanks for the detailed review!
> 
> I'm going to consider The term “exposes” is used several times, without saying to whom as a stylistic suggestion, and decline to address. I don't think there's a better way to say this without making the flow much more awkward. Please reopen this issue after closure if you disagree strongly.
> —
> 

I am quite willing to read it this way, this issue should be closed,

Gorry
