### ISSUE TITLE
applicability: ID Nits: 2119 Terminology

### ISSUE THREAD

**Issue by seanturner** [quicwg/ops-drafts#188]
There are two paragraphs that include 2119-language:

    RFC 2119 keyword, line 146: '...   case it is RECOMMENDED to abort the...'
    RFC 2119 keyword, line 491: '...e application is RECOMMENDED.  For exa...'
Should these be made lowercase or is a 2119 paragraph needed?

**Comment by mirjak** [comment]
I thought we changed everything to lower case. I will check those.

**Comment by britram** [comment]
Apparently already fixed by other committed PRs.
