### ISSUE TITLE
App: End of Sect 2: RFC2119 Keyword?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#192]
I think the following sentence has issues:
“In case it is RECOMMENDED to abort the connection, allowing the application to present a suitable prompt to the user that secure communication is unavailable.”
- I’m not sure I understand “In case”
- I’m not sure this should be upper case RFC2119, unless we decide to also make normative recommendations in other places.
- “allowing”..”unavailable” makes this award to read.

**Comment by seanturner** [comment]
2119 issue also noted in #188.
