### ISSUE TITLE
App: Sect 4.3. Flow Control - we should have a subsection also encouraging timely credits

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#193]
Issue: Sect 4.3. Flow Control - we should have a subsection also encouraging timely credits

This ID discusses flow control deadlock, whichI think  is important. I suggest we should also note that timely release of flow control credit is also important (QUIC transport has some text to point to). This need is evident when the path has a large RTT, and there can be a large BDP, where the whole of operation of QUIC can be dominated by the way in which the application manages the flow credit. This might not be obvious, because the equivalent rwnd update in TCP is handled by the transport rather than the application.

**Comment by mirjak** [comment]
The point is the audience for this draft is applications that use a quic library. I would assume that the actual credit handling is performed in the transport/in quic directly, usually without an interface for the application to directly impact it.

Do you propose the application should have more direct impact on flow credit handling?

I guess we can add a pointer to the right section in the transport draft but not sure we should/can say more here...?

**Comment by ianswett** [comment]
I agree this seems mostly like a QUIC transport/library issue and I wouldn't expect the application to have much control here.

I can imagine applications setting a max value?

**Comment by LPardue** [comment]
I generally agree with Mirja and Ian. However, on a closer inspection of this section I think it would benefit from a crisper definition of what it means to read data vs. process data. Its a reasonable application mapping implementation design to read data out of the transport in order to release flow control but still buffer it (or just dropping it on the floor) in application space before processing that as application data.

**Comment by mirjak** [comment]
@LPardue  can you propose text?

**Comment by gorryfair** [comment]
I'm content that flow control is something the libraries need to get correct - the TCP people spent energy to get this automated, although QUIC's multi-streaming makes the trickier. 

Lucas text suggestion would improve things by making it clearer how the API is intended to be used.

**Comment by mirjak** [comment]
@LPardue ?

**Comment by LPardue** [comment]
I will add some text (just need to find the time).
