### ISSUE TITLE
Padding explanation needs to mention DPLPMTUD

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#194]
“Padding is used by QUIC to ensure” - please add a sentence that DPLPMTUD is another reason why you might expect QUIC Padding of specific packets after connection establishment, and refer to section in QUIC transport - or people may have a surprise when they suddenly see big probe packets in their logs:-)

**Comment by mirjak** [comment]
I thought that this is what the sentence is about? The whole sentence says:

"Padding is used by QUIC to ensure that the path is capable of transferring datagrams of at least a certain size, ..."

We can add a reference to the right section in the transport draft but sure we need another sentence?

However, your point about being surprised to see big packets probably rather belongs into manageability...?

**Comment by gorryfair** [comment]
Ah sorry: I was trying to highlight that there are two places where I think QUIC might be expected to use padding... in the initial connection ... to verify the path supports the minimum size, and later whenever DPLPMTUD is invoked, to probe to check for a larger size. Two section refs would likely be useful.

... Yes, it could be mentioned in manageability - since often QUIC packets might be rather uniform in size with occasional DLPMTUD probes?

**Comment by mirjak** [comment]
I created a PR to add references to the respective sections in the QUIC transport draft. Explaining in detail what padding is used for internally in QUIC wasn't really the point here. However, it's probably correct that the sentence should not just omit one usage (PLDMTUD) and reference probably don't hurt.

Do we need still something for manageability? Or is that, at least partially, already addressed by #212 ?
