### ISSUE TITLE
App: Port Usage uses RFC2119 word?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#195]
Issue: “and use of the UDP port number corresponding to the TCP port already registered for the application is RECOMMENDED”.
I agree with the intent, but here an RFC2119 keyword is used, but is this intended, and can this please cite the RFC that says this rather than just stating this.

**Comment by seanturner** [comment]
Similarly noted in #188

**Comment by mirjak** [comment]
PR #211 removes normative language and says "usually ... appropriate" instead. Is that okay? Or should the wording be stronger?
