### ISSUE TITLE
App: ... interference by network elements such as firewalls

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#196]
The ID said: “blocking or other interference by network elements such as firewalls”
- I think this language could be seen as having a little attitude that could be avoided. I suggest replacing “interference”, and instead say that this can change the forwarding policy. This also extends it to include action from QoS policies and service level agreements.
“by network elements such as firewalls that rely on the port number for application identification.”
- I’d prefer “use” to “rely” … because they might well use other heuristics in future if they do prove more useful to classify sessions/packets.

**Comment by mirjak** [comment]
Is the wording in #213 better/good?
