### ISSUE TITLE
App: What does "prime a CC" mean?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#197]
The text says: “or prime the congestion controller in preparation for switching to the new path.” 
- what does prime mean?
-  and which section explains this function  in the QUIC spec?

**Comment by mirjak** [comment]
The idea here is that you can already e.g. estimate RTT or even open the congestion window before you switch. There was already some discussion previously (seePR #122) if we want to have this in the document or say more or less. Maybe a question to the rest of the wg (in the next meeting)...?

**Comment by gorryfair** [comment]
Unsure about this in this ID: Isn't that suggesting a transport extension/mechanism update... rather than the applicable use?

**Comment by mirjak** [comment]
I don't think it needs an extension. It can simply be done by the client. It's definitely not appropriate to specify a concrete algorithm in this document but it's just listed as one of the things that padding can be used during mitigation.

**Comment by gorryfair** [comment]
I'm really unsure about why text about priming is here and where the advice is located. I don't dispute that it can be done, or even that if done appropriately it can help, however it could also be done in a way that might also hinder. If PR 122 removes this word, then this topic can be discussed elsewhere in RFCs.

**Comment by mirjak** [comment]
@gorryfair PR #122 was already merged a long time ago. I was just point at it to say that there has been previous discussion. As the label indicates, we plan to bring the for discussion to the meeting.

**Comment by martinduke** [comment]
CC priming seems like an issue entirely internal to the QUIC implementation. Why should applications know or care about it?

I suggest we simply delete this.

**Comment by martinthomson** [comment]
I like @martinduke's suggestion.

**Comment by mirjak** [comment]
#291 is my proposal. It doesn't take about priming/pre-heating anymore but it says what's possible and why this icould be interesting for an application.

**Comment by mirjak** [comment]
PR #291 was merged.
