### ISSUE TITLE
App: Ref: Should the text ion DSCP also cite RFC7657?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#198]
Section 10: DSCP.

The advice and some use cases seem similar to that described in RFC7657. I suggest this is cited here.

**Comment by mirjak** [comment]
Not sure. RFC7657 is very specific to RTP traffic...

**Comment by gorryfair** [comment]
OK.

**Comment by gorryfair** [comment]
So sorry - my memory failed - I meant: RFC 8837, specifically as a reference to the advice therein which explains:  "if multiple flows
   are multiplexed using a reliable transport (e.g., TCP), then all of
   the packets for all flows multiplexed over that transport-layer flow
   MUST be marked using the same DSCP value."

**Comment by mirjak** [comment]
This sentence in RFC 8837 refers to rfc7657 section 6 which basically has the same advise ("Should use a single DSCP for all packets within a reliable transport protocol session"). We give the same recommendation here but not sure we need RFC8837 or RFC7657 to back this up. Also with QUIC, multiplexing is done in the QUIC layer which make it even harder for he application to try and apply different code points. I still think both rfc8837 and rfc7657 are quite RTC specific.

**Comment by gorryfair** [comment]
So... if you looked at this and think references to the use of DSCPs are sufficient guidance, this issue can be closed.
