### ISSUE TITLE
App: Sec 14: Security Considerations reference to transport BCP?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#201]
The Security Considerations of many transport RFCs have a reference to transport behaviour on (infrastructure implications) - such as a simple cite to the security considerations of RFC8085.... on transport aspects of using a UDP-based transport.

- This section could also refer to any text for the resolution  Issue #200 - i.e. QUIC validates ICMP before it is used?

**Comment by mirjak** [comment]
I looked at the security section of RFC8085 and I don't think these apply to an application that uses QUIC as they are address by QUIC itself in the protocol spec.

Or do you have anything specific we should point out here?

**Comment by mirjak** [comment]
@gorryfair indicated offline that this can be closed. He was trying to figure out if there is anything to consider regarding e.g. datagram support in QUIC. However, datagrams are still congestion controlled, so that should be reasonably safe.
