### ISSUE TITLE
Streams section could discuss in-order delivery assumption

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#215]
Though the specification does not insist upon it, most implementations will assume that stream data is reliably delivered in order.  This means that senders will send until every byte is delivered or they decide to reset the stream (possibly based on STOP_SENDING).  And it means that receivers won't make data available until a contiguous span of bytes starting at the last unread offset are available.

Implementations might act differently, but variations from this behaviour would need to be agreed by both endpoints.

**Comment by mirjak** [comment]
@martinthomson  can you propose text?
