### ISSUE TITLE
ALPN doesn't enable use of other ports

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#217]
> For example, HTTP/3 ([QUIC-HTTP] Sections 3.2 and 3.3) specifies the use of ALPN [RFC7301] for service discovery which allows the server to use and announce a different port number. 

I think that this refers to Alt-Svc (RFC 7838), which is mentioned in [Section 3.1.1](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-http-alternative-services).  You might also mention the not-yet-done SVCB record, but that might not be a good idea if you like the idea of publishing this.

**Comment by mirjak** [comment]
SVCB record would just be an informational reference, no? So that shouldn't hold up publication. In this case I'd be okay to provide a pointer.

**Comment by mirjak** [comment]
What do you meant by "ALPN doesn't enable use of other ports"?

**Comment by martinthomson** [comment]
The text here says "specifies the use of ALPN for service discovery which allows the server to use and announce a different port number".  ALPN is not a service discovery mechanism, it's a protocol selection mechanism.  ALPN is completely orthogonal to choice of ports.

The purpose of ALPN is for client and server to agree on the protocol that is used.

Your change to references in #250 won't fix this issue.  It does correctly cite the Alt-Svc sections of HTTP/3, but the surrounding text still says ALPN.
