### ISSUE TITLE
Multiple error code spaces

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#218]
> Application error codes are expected to be defined from a single space that applies to all three frame types.

This is true, but there is nothing inherent to the design that prevents RESET_STREAM (and STOP_SENDING) from using a different code space from CONNECTION_CLOSE.  Though we have the policy in HTTP/3 that any stream error can become a connection error, the same isn't necessarily true of other protocols.

Maybe we cab just avoid mentioning this possibility..,

**Comment by mirjak** [comment]
I don't think I have a strong opinion on removing or keeping this sentence. Would it be any better if we say:

"Application error codes are recommended to be defined from a single space that applies to all three frame types."

?

Or is there any other guidance we can or want to give to application designer about the use of error codes?
