### ISSUE TITLE
Gotta intercept

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#230]
> Since QUIC's wire image [WIRE-IMAGE] is integrity protected and not modifiable on path, in-network operations are not possible without terminating the QUIC connection, for instance using a back-to-back proxy. Proxy operations are not in scope for this document. A proxy can either explicit identify itself as providing a proxy service, or may share the TLS credentials to authenticate as the server and (in some cases) client acting as a front-facing instance for the endpoint itself.

The point of [the first sentence here](https://quicwg.org/ops-drafts/draft-ietf-quic-manageability.html#section-1-4) is a little odd, because it seems to imply that ALL operations require access to the information that is integrity- or confidentiality-protected.  That's clearly not the case, I think, as it is merely pointing out that if you want to modify data, then you have to be an endpoint.

I think that this might be better phrased as:

> Since QUIC's wire image {{WIRE-IMAGE}} is integrity protected, in-network operations that depend on modification of data are not possible without the cooperation of an endpoint.  Network operation practices that alter data are only possible if performed as a QUIC endpoint, which might be possible with the introduction of a proxy.  Proxy operations are not in scope for this document.

Note: This drops the last sentence of the original paragraph.  If proxying is out of scope, then it doesn't help to talk about it so much.  The point about cooperation should do.

**Comment by mirjak** [comment]
Created a PR based on your proposed text but added some of the information about proxies to make it more clear what kind of proxies we are talking about.
