### ISSUE TITLE
0-RTT is not limited by the initial congestion window

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#235]
> The amount of 0-RTT protected data is limited by the initial congestion window, typically around 10 packets [RFC6928].

However there are cases where the congestion window can increase when 0-RTT continues to be sent.  Some involve packet loss and so probably won't result in a net increase in the window, though the total number of packets might still exceed the initial window size.  Others, like TLS HelloRetryRequest or large certificates, involve additional round trips in the handshake.

The total amount of 0-RTT is also limited by remembered flow control values, though this is indirect as this counts stream data only and packets might be further padded.

**Comment by gorryfair** [comment]
The original text sounds correct - cwnd doesn't limit the total number of packets sent when some of those packets are declared lost  - although we might want to clarify how the sender can still "retransmit" new packets in later RTTs.

**Comment by martinthomson** [comment]
I read this as saying that if your initial congestion window is 10 packets, then you can't send more than 10 packets of 0-RTT.  That is not the case, even if it might commonly be that way.  A client can send 0-RTT over multiple RTTs if you consider HelloRetryRequest and large handshake flights.  In the extreme, there is no real limit to the amount of 0-RTT packets that can be exchanged.
