### ISSUE TITLE
QUIC is distinguishable, but it's limited

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#237]
> The QUIC wire image is not specifically designed to be distinguishable from other UDP traffic.

This isn't entirely true, because we made specific allowances in QUIC version 1 to make QUIC distinct from realtime protocols, like STUN and RTP.  That is why the fixed bit is there.

I don't have a good suggestion here; it's a key sentence, but it's wrong.

**Comment by gorryfair** [comment]
From an OPS point of view, I'd like to read the answer to: Can configurations be deployed that rely on a bit/pattern to classify QUIC traffic - i.e., current and future versions that the IETF expects to make?

**Comment by mirjak** [comment]
The QUIC bit is discussed two paragraphs down. Intention here at this sentence at the beginning of the section was to say that there is no easy way to identify QUIC. The QUIC bit is only used for multiplexing with a set of known other transports on the same port. However, it still doesn't ensure you that you are looking at QUIC traffic.

I think the text is basically correct. However, if anybody has a proposal to tweak the sentence, please let me know!

**Comment by mirjak** [comment]
@gorryfair this section is meant to answer your question with no. If that is not clear, can you propose what's missing?

**Comment by gorryfair** [comment]
Your answer works for me. I re-read and have no request to change.
