### ISSUE TITLE
Maybe you can link flows sometimes, but not always

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#239]
> Negotiated version cannot be identified for flows for which a handshake is not observed, such as in the case of connection migration; however, these flows can be associated with flows for which a version has been identified; see Section 3.4.

This implies that the version of QUIC being used in a given flow can be determined simply by linking that flows to one with a handshake.  That assumes that all the work we did to make flows difficult to link was for naught.  Maybe "can" should be a "might" or something along those lines.

I don't really like the implication that the attempt be made to link flows like this either.

**Comment by martinthomson** [comment]
In addition to this, the following text from Section 3.4 is not precise enough to be correct:

> An observer keeping flow state can associate a connection ID with a given flow, and can associate a known flow with a new flow when when observing a packet sharing a connection ID and one endpoint address (IP address and port) with the known flow.

The assumption that the same flow persists might be good in some cases, but this does not necessarily hold in the case that the endpoint address is used by an endpoint that requires non-zero-length connection IDs.  This needs to be more precise if the claim is to hold.

**Comment by mirjak** [comment]
Not sure what you mean by your second comment here. Of course if there is no connection ID you cannot associate it to anything...?

What's missing? Can you propose something?

**Comment by martinthomson** [comment]
On re-reading, it seems to be a little clearer.  It seems to be saying that an observer can match a particular connection ID with a flow and then, if the flow changes address at only one end without changing the connection ID, then it was subject to rebinding and can be assumed to be the same flow.

However, it needs to specify that the connection ID association needs to be directional.  Maybe that is assumed, but it should be stated.  And it needs to say that this is unlikely to apply when the connection ID is empty.
