### ISSUE TITLE
No need to repeat connection ID requirements

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#243]
[This text](https://quicwg.org/ops-drafts/draft-ietf-quic-manageability.html#section-2.6-2) repeats requirements from the transport spec unnecessarily.

> Server-generated connection IDs should seek to obscure any encoding, of routing identities or any other information. Exposing the server mapping would allow linkage of multiple IP addresses to the same host if the server also supports migration. Furthermore, this opens an attack vector on specific servers or pools.

It might be easier to just strike this.

**Comment by mirjak** [comment]
This is supposed to give advice to network operators e.g. in a load balancing setup where connection IDs are maybe generated centrally and distributed to the servers.

**Comment by martinthomson** [comment]
The surrounding text does. This paragraph does not.

**Comment by chris-box** [comment]
> This is supposed to give advice to network operators e.g. in a load balancing setup where connection IDs are maybe generated centrally and distributed to the servers.

I didn't think network operators who are in control of one of the endpoints would be considered in scope for this I-D. Surely the whole point is to advise network operators about what they should do with traffic they cannot hope to decrypt? If server endpoint operators are in scope, the Introduction should be revised. If they are not in scope, I could propose some words that essentially say "Don't bother trying to infer information from specific parts of the connection ID, for these reasons."

**Comment by mirjak** [comment]
Okay, I think I see the problem now. Is #310 better?
