### ISSUE TITLE
Section 9 algorithm

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#244]
I think that this section should be removed.

(As an aside, calling something an appendix doesn't make it so.  You can put the text under `--- back` to make it an appendix proper.)

**Comment by mirjak** [comment]
I we didn't get an further comments about this issue, proposal is to close without action.

**Comment by britram** [comment]
Now properly in the appendix. Closing for now due to lack of additional feedback. Please reopen if there are other opinions to remove.

**Comment by martinthomson** [comment]
I'd appreciate a defense for the text.  I don't think that we need to be documenting how to identify Google QUIC versions. Especially as those will soon disappear from the Internet.
