### ISSUE TITLE
Appl: TLS over TCP cannot be supported...

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#258]
I couldn't immediately parse, and I'm assuming this is a NiT, but I can always be surprised by nuances in security-related text, so I'm writing this as an issue:
/If TLS over TCP cannot be supported, the connection should be aborted instead, in order to enable the application to present a suitable prompt to the user that secure communication is unavailable./
If TLS over TCP cannot be supported, the connection should be aborted, and the application should present a suitable prompt to the user that secure communication is unavailable./

**Comment by mirjak** [comment]
I guess we can remove the "instead" but why did you chance the "in order to"? The reason to abort instead of just moving on without security is, so that the application recognises and can tell the user.

**Comment by mirjak** [comment]
@gorryfair ?

**Comment by gorryfair** [comment]
OK on removing instead
Is this better?:
/If TLS over TCP cannot be supported, the connection should be aborted, and the application then ought to present a suitable prompt to the user that secure communication is unavailable./
