### ISSUE TITLE
QUIC doesn't necessarily expose Stream IDs?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/ops-drafts#263]
The ops draft currently says:

> While a QUIC implementation must necessarily provide a way for an application
to send data on separate streams, it does not necessarily expose stream
identifiers to the application (see, for example, {{QUIC-HTTP}}, Section 6)
either at the sender or receiver end, so applications should not assume access
to these identifiers.

I don't see anything in Section 6 of HTTP/3 to support that claim.  In fact, HTTP/3 uses Stream IDs in the GOAWAY frame to indicate the last request the server processed; both client and server will require access to the identifiers of streams, or that information is impossible to generate and useless to receive.

The constraint that I tried to use when writing the HTTP draft was that the application layer has no control over the assignment of Stream IDs.  However, once it has requested and been given a stream, it can retrieve the ID of that stream and use it to reference the stream at the application layer.

By the same token, the application layer shouldn't assume it understands the relationship between stream types and Stream IDs; that may change in a future QUIC version, and it should rely on querying the stream properties to identify types.

**Comment by mirjak** [comment]
Actually writing these constraints/assumptions down would be nice. Can you try to create a PR, @MikeBishop ?

**Comment by mikkelfj** [comment]
I don't think there should be formal constraints on QUIC per se. It is largely up to both the QUIC application layer protocol, and also the specific QUIC API interface. QUIC application layer protocols such as HTTP/3 can have expectations the QUIC API and these should be documented.
