### ISSUE TITLE
Is HTTP/2 our prioritization poster-child?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/ops-drafts#264]
> an application protocol that runs on top of QUIC can define explicit messages
for signaling priority, such as those defined for HTTP/2

First, if we retain this comment, it should probably have a reference to RFC 7540 and the appropriate section.

However, as @mirjak noted in reply to a previous issue, this document is about QUIC, not TCP; the use of HTTP/2 as an exemplar seems out-of-place, particularly since we're actively deprecating that priority scheme.  Perhaps a reference to draft-ietf-httpbis-priority would be more appropriate?

**Comment by ianswett** [comment]
I agree that a reference to draft-ietf-httpbis-priority would be more appropriate.

**Comment by mirjak** [comment]
Yes, sounds good. I'll create a PR if no-one else does it before me.
