### ISSUE TITLE
Version Negotiation integrity

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/ops-drafts#265]
> QUIC provides integrity protection for its version negotiation process.  This
process assumes that the set of versions that a server supports is fixed.  This
complicates the process for deploying new QUIC versions or disabling old
versions when servers operate in clusters.

This functionality was removed from -transport, and appears to refer to text in draft-ietf-quic-version-negotiation, but that draft isn't referenced at all.

**Comment by mirjak** [comment]
I can add a reference to draft-ietf-quic-version-negotiation and make clear that this is an extension and not part of the base spec.
