### ISSUE TITLE
Manageability flight naming

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/ops-drafts#276]
> In the nominal case, the QUIC handshake can be recognized on the wire through at
least four datagrams we'll call "QUIC Client Hello", "QUIC Server Hello", and
"Initial Completion", and "Handshake Completion", for purposes of this
illustration, as shown in {{fig-handshake}}.

I mean, you can call them that for reference purposes, but there's no such thing as a "QUIC Client Hello" (or ClientHello).  Calling something "Initial Completion" when it might not contain any Initial packets might confuse people when they go looking for more details.

Maybe "Client Initial," "Server Initial," "Client Finished," and "Server Finished"?  It mixes layers, but those are at least things that occur in the referenced packets.

**Comment by martinthomson** [comment]
Or, to avoid using TLS message names consistently, s/Finished/Confirmation

**Comment by chris-box** [comment]
Should I conclude from the absence of comment since February that we are all reasonably content with "Client Initial", "Server Initial", "Client Completion", and "Server Completion"? If so I'm happy to create the PR to save Brian a job. But I don't want to do that if these are not the best names.

**Comment by mirjak** [comment]
This was assigned to Brian has he wanted to take a stab.

**Comment by chris-box** [comment]
That's fine I'll leave it to Brian.
