### ISSUE TITLE
Do we need to say more about padding and DPLPMTUD in manageability?

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#278]
This issue is branch of #194 where @gorryfair say:

"... Yes, it could be mentioned in manageability - since often QUIC packets might be rather uniform in size with occasional DLPMTUD probes?"

@mirjak said:

"Do we need still something for manageability? Or is that, at least partially, already addressed by #212 ?"

**Comment by gorryfair** [comment]
This is a separate note to call out that a QUIC sender can probe the path to determine whether the PMTU can be increased. 

When #212 finally converges to text, we should check this is also covered.

**Comment by britram** [comment]
This was covered in #212, which is now merged.
