### ISSUE TITLE
Document how a server cluster might be upgraded and rolled back

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/ops-drafts#28]
Moving this from quicwg/base-drafts#504 to here.

**Comment by mirjak** [comment]
@janaiyengar @ianswett can one of you maybe provide some text?

**Comment by martinthomson** [comment]
[This](https://github.com/quicwg/base-drafts/pull/1901#discussion_r228354726) is probably exactly what needs to be said for this issue.
