### ISSUE TITLE
Clarify Stream ID assignment

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/ops-drafts#283]
Follow up to comment on #270 

The current text:

> The method of allocating stream identifiers to streams opened by the application
might vary between transport implementations. Therefore, an application should
not assume a particular stream ID will be assigned to a stream that has not yet
been allocated.  For example, HTTP/3 uses Stream IDs to refer to streams that
have already been opened, but makes no assumptions about future Stream IDs or
the way in which they are assigned.

Specifically "An application should
not assume a particular stream ID will be assigned to a stream that has not yet
been allocated. "

This highly depends on the application protocol, not the QUIC transport API. It may be that a given QUIC transport protocol is unable to support the requirements of a QUIC application protocol, but it is the app protocol that decides. If a given  QUIC transport API only supports "OpenNextStreamOfType(x)" that might be enough to support HTTP/3. But it should be be that all app protocols follow the same constraints.

However, it is reasonable to recommend that application level protocols attempts to avoid a dependency on a specific stream ID in order to be able to target a broader range of QUIC transport libraries and to avoid unnecessary dependencies while at the same time permitting this for specific use cases.

**Comment by mirjak** [comment]
I not sure what you are missing here or what you think should be changed. For me the text is inline with what you say, which basically is: to be on the safe side you better make no assumption about how non-yet assigned ID will be used because there is no unified way how this is specified in the protocol spec. So, basically saying even if the interface seem to provide that, be careful here!

**Comment by mikkelfj** [comment]
The text

"An application should
not assume a particular stream ID will be assigned to a stream that has not yet
been allocated. "

basically says that you should not design protocols that rely on stream IDs have any particular meaning. But you could easily design such protocols safely, but it will only work for transport libraries that permit such close coordination.

Personally I think it is best to avoid such dependencies in most cases, but that shouldn't prevent special purpose protocols from existing. For example, a telemetric protocol might define that streams 1 through 100 (modulo stream type) each indicate a log level of implied severity.

**Comment by mirjak** [comment]
This is a recommendation not a normative SHOULD. We are only trying to provide guidance but if you are a specialised application and you know what you are doing you can of course do that.

**Comment by mirjak** [comment]
@mikkelfj can we close this issue or would you like to propose a wording change?

**Comment by britram** [comment]
Seeing no further action/suggestion, closing. Please reopen if there's a concrete change to make.
