### ISSUE TITLE
draft-ietf-quic-manageability-10 Feedback

### ISSUE THREAD

**Issue by jaredmauch** [quicwg/ops-drafts#289]
Some feedback:

Sections 4.1, 3.5, 3.6 and 3.7 are all related and related to the same underlying principle, related flows and the need for them to be delivered in a predictable and consistent manner.  Is there a reason these are not in their own section or more closely tied to each other?  Are there any additional fields that should not be included in the flow calculation for future hardware or software implementors?

**Comment by britram** [comment]
3.x sections talk about things on a per-field basis, while 4.x sections address specific network management use cases, so there's a reason there's a little redundancy here.

We might look into grouping 3.5-3.7 as subsections of a new overarching section, though...

**Comment by mirjak** [comment]
@jaredmauch can we close this issue?
