### ISSUE TITLE
Describe how and why a server might choose connection IDs

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/ops-drafts#29]
Moving https://github.com/quicwg/base-drafts/issues/514 to the ops repo.

**Comment by britram** [comment]
see also #11 -- in any case the text that is there now is not great.

**Comment by mirjak** [comment]
@janaiyengar can you please review the existing text (orginially provided by @igorlord) and state what else is needed?

**Comment by britram** [comment]
#51 fixed this
