### ISSUE TITLE
Applicability could say more about ALPN

### ISSUE THREAD

**Issue by LPardue** [quicwg/ops-drafts#292]
Sorry I missed this during the WGLC. https://quicwg.org/ops-drafts/draft-ietf-quic-applicability.html#section-6 contains a lot of good stuff but it seems like it could say more about ALPN.

1) As an editorial comment ALPN is mentioned without expanding the acronym. The term `ALPN token` is used, which doesn't seem to be defined anywhere other than the HTTP/3 specification (which might be a problem or not)

2) More substantial, there isn't really mention about any of the TLS or negotiation aspects of ALPN. We might see people try to offer multiple Application Protocols on the same UDP port, and using ALPN to select from them. Maybe this is more likely when QUIC can operate as both a stream-based and datagram-based protocol. 

3) Related to 2, new application protocols over QUIC need an ALPN protocol identifier. This is distinct from the Alt-Svc discussion in Section 6; since other protocols won't use Alt-Svc, they might overlook things. The ALPN space is large but we might benefit from some text that gives people pointers on how to register the ALPN IDs they want to use before someone gets them. For reference, I started a list of protocols at https://github.com/quicwg/base-drafts/wiki/ALPN-IDs-used-with-QUIC. Not all of those need formal registration but it is a nice illustration.

**Comment by LPardue** [comment]
I'm unfortunately not coming up with some useful/actionable text here. Maybe @martinthomson or @MikeBishop has some insight that could help?

**Comment by MikeBishop** [comment]
It feels like the best way to incorporate this is to expand the "protocol doesn't imply port" discussion to also include "port doesn't imply protocol" before concluding with "not being able to safely make this inference is hard."  #302 has a first stab at this, though it doesn't cover as much as @LPardue first suggested.  Feel free to expand on it.
