### ISSUE TITLE
UDP Policing or maybe Blocking?

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#294]
@ianswett said in PR #272 on the section title "UDP Policing":

"Policing has a slightly different meaning(token bucket policer) that's widely used, so can we find a different term in this context?"

**Comment by chris-box** [comment]
Looks like #305 will resolve this.

**Comment by mirjak** [comment]
Yes, #305 is supposed to resolve this. Not sure why this is not correctly linked...

**Comment by mirjak** [comment]
#305 is merged
