### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#3]
Someone with ownership rights needs to hit the button on [circle](https://circleci.com/dashboard) (not travis).

**Comment by mnot** [comment]
I think I pressed the right button...

**Comment by martinthomson** [comment]
The first build was clean.  To get the editors' drafts, we need someone to put a token in an environment variable called GH_TOKEN.

**Comment by martinthomson** [comment]
Not seeing anything running for my latest PR.  That's probably a misconfiguration.  Is Circle configured to build pull requests?  It should be.

**Comment by mnot** [comment]
"Build forked pull requests", right?

![screen shot 2017-06-21 at 1 34 44 pm](https://user-images.githubusercontent.com/74384/27365950-6e69f1e8-5686-11e7-976c-f4d51e98f170.png)

**Comment by martinthomson** [comment]
Yep.

**Comment by mnot** [comment]
Done.

**Comment by britram** [comment]
this seems to work now; closable?

**Comment by martinthomson** [comment]
It doesn't look like gh-pages is being updated automatically, which means that the issues aren't being saved either.

@britram, are you manually updating gh-pages?  Are you happy continuing to do that?  If so, I will close this.

**Comment by britram** [comment]
I think I found the issue here; needed to make setup-ghissues...

**Comment by britram** [comment]
CI seems to work for PRs now, at least.
