### ISSUE TITLE
Merge sections 4.5 (Filtering Behavior) and 4.6 (UDP Policing)

### ISSUE THREAD

**Issue by britram** [quicwg/ops-drafts#301]
These two sections are slightly redundant, and could easily be merged because the advice they give is more or less identical.

**Comment by gorryfair** [comment]
I think better to group these two!

The current filtering text describes "possible packet filtering behaviors that relate to NATs". I suggest an initial series of packet *ALSO* traverse other domain edge devices (such as DDOS detection, NIDS, etc) in the same way, so we should be clear that NAT/NAPT is an example:-)

**Comment by britram** [comment]
discussion on 19 April editor's meeting: there's been a lot of minor editorial refactoring that improves the flow of the doc, making this merge less necessary. 

Still need to make sure we have examples other than NAT, though.

**Comment by britram** [comment]
multiple-examples fixed in #321
