### ISSUE TITLE
ACK generation

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#330]
There is text in the transport document on reducing ACK frequency.  I think that that is sufficient.  As this is more about performance tuning for implementers of the QUIC transport itself, it might be best to remove this section.

**Comment by gorryfair** [comment]
I am going to argue aganist this. It's a valid operational concern for a current network operator (at least any operator that does radio capacity assignment) and an apps developer. Although QUIC ACKs are something an endpoint might/ought to optimise, it was not really resolved in the core spec. QUIC can be more greedy on return capacity than TCP practically would when on-path mitigations are used.

**Comment by mirjak** [comment]
This section was added based on comments from previous last call. I wouldn't want to remove it based on only one comment here. If more discussion is needed, we can bring it to the list.

**Comment by LPardue** [comment]
I might agree with Martin.

The document states "... Its intended audience is designers of application protocol mappings to QUIC, and implementors of these application protocols", and arguably the concerns about ACK frequency are not the concerns of the target audience. What can an application layer person do about this realistically? I don't think we they can change the app protocol design around this transport behaviour.

That's not to say that the advice is bad. But I think the section would be stronger if it said plainly the caveat that Gorry just mentioned - applications using QUIC may find that the return traffic is more verbose than TCP, due to the differences in ACK generation and optimizations that have been applied.

**Comment by ianswett** [comment]
I have mixed feelings on this, but I think there may be some things worth saying that are applicable to this audience.

I think we need to change the existing text to clearly state that applications using QUIC may find that ACKs consume more resources, and cite transport if possible.

Additionally, I think it's worth calling out that the ACK policy of QUIC v1 (without something like ACK-frequency) is designed to be similar to TCP, and may not be optimal for the full set of applications that QUIC can support.  Realtime/WebRTC as well as VPN applications come to mind.

**Comment by mirjak** [comment]
@LPardue there is also a section on ACK traffic in the manageability statement:

```
Distinguishing Acknowledgment Traffic

Some deployed in-network functions distinguish pure-acknowledgment (ACK) packets from packets carrying upper-layer data in order to attempt to enhance performance, for example by queueing ACKs differently or manipulating ACK signaling {{?RFC3449}}. Distinguishing ACK packets is possible in TCP, but is not supported by QUIC, since acknowledgment signaling is carried inside QUIC's encrypted payload, and ACK manipulation is impossible. Specifically, heuristics attempting to distinguish ACK-only packets from payload-carrying packets based on packet size are likely to fail, and are not recommended to use as a way to construe internals of QUIC's operation as those mechanisms can change, e.g., due to the use of extensions.
```

**Comment by mirjak** [comment]
@gorryfair @ianswett can anybody propose a PR? However, I think this would be a PR against the section on ACK traffic in the manageability statement if the intended audience is network operators.

**Comment by mirjak** [comment]
For the applicability statement I created PR #386 providing some more explanations. Does that help or do people still prefer to drop/move more considerations to the manageability statement? @gorryfair @martinthomson @ianswett @LPardue

**Comment by ianswett** [comment]
Thanks for the PR, I think it's heading in a fairly good direction.  But if people want to remove it from this draft, I'm not going to stand in your way.
