### ISSUE TITLE
QUIC *is* designed to be distinguishable

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#339]
> The QUIC wire image is not specifically designed to be distinguishable from other UDP traffic.

It is specifically designed to allow for multiplexing of QUIC with real-time protocols.  See RFC 7983.

**Comment by SpencerDawkins** [comment]
@martinthomson, is this issue conflating what endpoints can distinguish and what anyone else can distinguish?

I'm guessing that's the case, but it would be good to be clear about this, especially in the ops drafts.

Again, I'm being informed here about what https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/35 in MOPS should say. So thank you for opening the issue!
