### ISSUE TITLE
HTTP/3 uses UDP port 443 by convention

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#340]
> HTTP/3 uses UDP port 443 by default

This is not entirely true.  As we have HTTPS records and Alternative Services, there is no case where HTTP/3 goes without a means of signaling a port number.  So there is no real "default" as far as it goes.  It's just that we reserved the number and we tend to use that port number by convention.

**Comment by SpencerDawkins** [comment]
For what it's worth, @LPardue and I were talking about this wrt https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/35 in MOPS, so the timing of this issue in QUIC was very helpful. Thank you for that. I'm using "by convention", at his suggestion.
