### ISSUE TITLE
Parsing Initials to get the DCID

### ISSUE THREAD

**Issue by martinthomson** [quicwg/ops-drafts#344]
... doesn't make it clear that only the Initial from the client (and only those sent before receiving packets from the server) contain a Destination Connection ID field that can be used to decrypt the packet.  Any initial from the server, or any initial sent by a client after receiving Initial packets from the server, probably won't work.

**Comment by martinthomson** [comment]
Hmm, this is the last paragraph.  Too late?

**Comment by martinduke** [comment]
More broadly, it would be nice if Sec 2.4 discussed the property that the server CID changes pretty much immediately. We wouldn't want people to bind to a 2-tuple of CIDs and have that immediately fail.

**Comment by mirjak** [comment]
@martinduke I create PR #376 based on your comment. Is that sufficient?

@martinthomson which section are you talking about?

**Comment by britram** [comment]
I think #380 will fix @martinthomson's comment here.
