### ISSUE TITLE
Handshake Illustration

### ISSUE THREAD

**Issue by britram** [quicwg/ops-drafts#35]
The manageability document should illustrate all the various packet sequences in a handshake, preferably with pretty pictures.

**Comment by mirjak** [comment]
Now the transport draft has these illustrations as well. However, I think we should still at them in manageability as well. Actually I would like to try the SVG format here. Anybody in for that?

**Comment by britram** [comment]
The handshake illustrations here should only concern themselves with the wire image, unlike those in the transport draft, but yes we should derive them from the transport draft. Happy to do these in ASCII as well as SVG.
