### ISSUE TITLE
Clarify coalescing and multiple packets in "The QUIC Handshake" section

### ISSUE THREAD

**Issue by ianswett** [quicwg/ops-drafts#352]
QUIC handshakes may or may not coalesce packets, which is stated, but I'm worried it could be missed by a reader.

I think it'd be good to clarify that any portion of the server or client flight could span multiple datagrams.

In particular, I'm worried this paragraph could mislead people, because unless the connection is resumed, the Handshake CRYPTO data typically spans multiple datagrams.  Similarly, the client or server's Initial can span multiple datagrams, though that's not currently common:
> A typical handshake starts with the client sending of a Client Initial datagram as shown in {{fig-client-initial}}, which elicits a Server Initial datagram as shown in {{fig-server-initial}} typically containing three packets: an Initial packet with the Server Initial, a Handshake packet with the rest of the server's side of the TLS handshake, and initial 1-RTT data, if present."

**Comment by mirjak** [comment]
@ianswett can you maybe propose a PR? :-)

**Comment by ianswett** [comment]
Yes, possibly later today after I finish reviewing the draft.

**Comment by mirjak** [comment]
@ianswett are you still planning to do a PR here?

**Comment by ianswett** [comment]
I will unless someone beats me to it, but I've been on paternity leave for 10 days.  @DavidSchinazi had some suggested text for the SNI section, but I can try to fix "The QUIC Handshake" and assume David's text is a good start for SNI.

**Comment by ianswett** [comment]
While writing the PR, I discovered a problem I'm not sure how to fix, which is how does an observer know when the handshake is complete for the server, given the server can start using 1-RTT keys immediately after receiving the client hello?

Receipt of the client's 1-RTT packet doesn't guarantee anything, because the server can't process it if it doesn't have keys.
