### ISSUE TITLE
Manageability: SNI extraction assumes a single CRYPTO frame

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/ops-drafts#358]
The [SNI extraction section of the manageability draft](https://datatracker.ietf.org/doc/html/draft-ietf-quic-manageability-11#section-3.4.1) mentions `parsing the QUIC CRYPTO Frame containing the TLS ClientHello`. This makes the assumption that INITIAL packets carry a single CRYPTO frame. That assumption might not always hold in modern browsers, so the text should clarify that any middlebox that wishes to extract the SNI MUST perform reconstruction of the crypto stream from one or more CRYPTO frames in one or more INITIAL packets. The current assumption might lead middlebox vendors to write deploy software that doesn't work if there are multiple CRYPTO frames. The section correctly states `There might be multiple CRYPTO frames` but that comes late in the section and doesn't detail what middlebox vendors should do about it.

That section also contains another incorrect assumption: `In QUIC version 1, the packet is expected to contain only CRYPTO frames and optionally PADDING frames`. There are other frame types that are legal in INITIAL packets and may be sent by browsers.

**Comment by mirjak** [comment]
The text already says the following now:

`There might be multiple CRYPTO frames. Finally, an extension might define additional frame types which could be present.`

Not sure when exactly this got added but I assume this is sufficient to address this issue? @DavidSchinazi @ianswett ?

**Comment by DavidSchinazi** [comment]
I don't think the new text fully addresses this issue.

In the new text, this statement is incorrect: `In QUIC version 1, the packet is expected to contain only CRYPTO frames and optionally PADDING frames.` What about PING frames for example?

Additionally, the client's first flight won't contain extension frames because the client has no way of knowing whether the server supports them so this statement is somewhat misleading: `Finally, an extension might define additional frame types which could be present.` What are middleboxes supposed to do if they see an unknown frame type, we should provide guidance there. I think we should just tell middlebox implementors to refer to that section of RFC 9000 and expect to parse all frame types, and fail parsing if they see a frame type they don't recognize.

And while we're at it, we should also mention that CRYPTO frames might be out of order.

**Comment by mirjak** [comment]
I would expect ping frame in the initial... so that sentence might still be fine. I think there could actually be extension frame in the first flight, e.g. if information was cached about the support of the extension.

In any case, can you maybe propose text @DavidSchinazi ?

**Comment by DavidSchinazi** [comment]
Extension caching doesn't work for initials because the server can still reject 0-RTT at this point.

How about this text:

> If the ClientHello is not encrypted, SNI can be derived from the client's Initial packet by calculating the Initial secret to decrypt the packet payload and parsing the QUIC CRYPTO frame(s) containing the TLS ClientHello.
>
> As both the derivation of the Initial secret and the structure of the Initial packet itself are version-specific, the first step is always to parse the version number (the second through fifth bytes of the long header). Note that only long header packets carry the version number, so it is necessary to also check if the first bit of the QUIC packet is set to 1, indicating a long header.
>
> Note that proprietary QUIC versions, that have been deployed before standardization, might not set the first bit in a QUIC long header packet to 1. However, it is expected that these versions will gradually disappear over time.
>
> When the version has been identified as QUIC version 1, the packet type needs to be verified as an Initial packet by checking that the third and fourth bits of the header are both set to 0. Then the Destination Connection ID needs to be extracted to calculate the Initial secret using the version-specific Initial salt, as described in Section 5.2 of [QUIC-TLS]. The length of the connection ID is indicated in the 6th byte of the header followed by the connection ID itself.
>
> To determine the end of the header and find the start of the payload, the packet number length, the source connection ID length, and the token length need to be extracted. The packet number length is defined by the seventh and eight bits of the header as described in Section 17.2 of [QUIC-TRANSPORT], but is obfuscated as described in Section 5.4 of [QUIC-TLS]. The source connection ID length is specified in the byte after the destination connection ID. The token length, which follows the source connection ID, is a variable-length integer as specified in Section 16 of [QUIC-TRANSPORT].
>
> After decryption, the client's Initial packet can be parsed to detect the CRYPTO frame(s) that contains the TLS ClientHello, which then can be parsed similarly to TLS over TCP connections. The client's Initial packet may contain other frames, so the first bytes of each frame need to be checked to identify the frame type, and if needed skip over it. Note that the length of the frames is dependent on the frame type, so it is necessary to refer to {{Section 18 of QUIC-TRANSPORT}}. Also note that there might be multiple CRYPTO frames, and they might not be in order, so reassembling the CRYPTO stream by parsing offsets and lengths is required. If an unknown frame type is encountered, it is impossible to know the length of that frame which prevents skipping over it, and therefore parsing fails.
>
> Note that subsequent Initial packets might contain a Destination Connection ID other than the one used to generate the Initial secret. Therefore, attempts to decrypt these packets using the procedure above might fail unless the Initial secret is retained by the observer.
