### ISSUE TITLE
Manageability: Detailed Review Comments - NiTs

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#362]
This issue captires a number of minor wording issues, references etc:

Operators should expect to observe packets with other version numbers as a result of various Internet experiments, future standards, and greasing.
- Since greasing might not be understood by all operations staff, a reference here would help, e.g.: RFC8701.

Style:
“four datagrams we'll call “
- why suddenly a use of “we”, can you reword to remove that?

This could be clearer:
“When the client uses 0-RTT connection resumption, 0-RTT data may also be seen in the Client Initial datagram, as shown in Figure 6.”
- what does “seen” mean? is “can be present” equivalent, in which case it is better than implying it is observable.

“will result in connection establishment failing later on.”
- Can we just remove the spurious word “on” at the end of the sentence?

“This allows rebinding of a connection after one of one endpoint experienced an address change”
- what is “one of one”?

“also supports migration which opens an attack vector on specific servers or pools.”
- add comma before “which” or use “that”?

Section 2.7 could refer to https://datatracker.ietf.org/doc/draft-ietf-tsvwg-transport-encrypt, (now in RFC-Ed) for examples of sequence number observation and alternatives for encrypted transports.

Section 3:
“This section addresses the different kinds of observations and inferences that can be made about QUIC flows by a passive observer in the network based on the wire image in Section 2.”
- This seems correct, although may be helpful to also say this observer does not have access to keying information.

Actually the set of possible things that can be done is more than the say, please add a reference
for example by queueing ACKs differently or manipulating ACK....
- It might be worth citing RFC3449 as example? or https://datatracker.ietf.org/doc/draft-ietf-tsvwg-transport-encrypt.
- Although other things also are done and also some links compress ACKs, etc there is a more modern view in:  per https://datatracker.ietf.org/doc/draft-ietf-tsvwg-transport-encrypt./.

The title here: 4.8. Quality of Service handling and ECMP 
- should this title be “ 4.8. Quality of Service handling and ECMP Routing”
- just to complete the concept of ECMP in the section title?

**Comment by gorryfair** [comment]
And ... 
The text says: “a particularly unwise behavior is to admit a handful of UDP packets and then make a decision as to whether or not to filter it”
- “it” is presumably “later packets in the flow”?

**Comment by britram** [comment]
...check first to make sure we didn't already merge a PR for these...

**Comment by mirjak** [comment]
> Operators should expect to observe packets with other version numbers as a result of various Internet experiments, future standards, and greasing.

> Since greasing might not be understood by all operations staff, a reference here would help, e.g.: RFC8701.

There was already a reference but should we rather replace "greasing" with "aliasing" and refer to draft-duke-quic-version-aliasing ?

**Comment by gorryfair** [comment]
My PR was #378.
