### ISSUE TITLE
Manageability: Not so trivial ACK detection for TCP

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#363]
The text says: “Distinguishing ACK packets is trivial in TCP,”
- arguably this is not trivial, since you need to handle data and ACKs and exclude implications of TCP options. I’d prefer to say “possible” than “trivial”.

**Comment by chris-box** [comment]
It's more than possible, it's easy.

I don't quite follow which TCP options you're referring to. I can only think of SACK, which just reduces the number of them.

Why is this not as trivial as "If only the ACK bit is set, and there's no payload, it's an ACK." ?
(Yes, truly bidirectional flows will have payload, but then I would argue they are not simple ACK packets.)

**Comment by gorryfair** [comment]
SACK adds an obvious widley deployed complication for TCP; ECN feedback also; some methods have simply used packet size. I know there are various forms ACK decimation/filtering/etc, some even delve into IP encaps to do this, I just don't want to convey a message that this "trivial" to get a good solution. The key point is that QUIC does not allow any of this without keying information.

**Comment by chris-box** [comment]
I see. So we need a word that says it's a bit more complex than "trivial", but still reasonably simple (esp. in comparison with QUIC). "Possible" would work.

**Comment by gorryfair** [comment]
Yes, "possible" is indeed fine. Shall I make a PR?

Gorry

**Comment by chris-box** [comment]
I'd say yes.
