### ISSUE TITLE
Manageability: Is dropping intended to be random?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/ops-drafts#365]
Section 4.6
“Further, if UDP traffic is desired to be throttled, it is recommended to block individual QUIC flows entirely rather than dropping packets randomly.”
- this implies “random”as a feature (rather than burst or flow-specific), I am not sure this was what I expected. 
But my real question is whether the drop really *intended* to be random? or burst? or uncorrelated? Should this be more like:
“Further, if UDP traffic is desired to be throttled, it is recommended to block individual QUIC flows entirely rather than dropping packets without considering the flow to which they belong.”
... this seems to be the point in the remainder of the section

**Comment by chris-box** [comment]
I think you're right; in a basic policer randomness is a consequence of the way it works, rather than being a goal.

Here we want to say don't drop packets indiscriminately; please consider which flow they belong to and drop some flows.

**Comment by britram** [comment]
this has been fixed in another editorial PR; s/random/indiscriminate/
