### ISSUE TITLE
Provide guidance on use of PING

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#37]
The transport draft says:

"The PING frame can be used to keep a connection alive when an application or application protocol wishes to prevent the connection from timing out. An application protocol SHOULD provide guidance about the conditions under which generating a PING is recommended. This guidance SHOULD indicate whether it is the client or the server that is expected to send the PING. Having both endpoints send PING frames without coordination can produce an excessive number of packets and poor performance."

Probably we should state this in the applicability statement as well...

**Comment by mirjak** [comment]
The transport draft also provides guidance on on the ping interval: 

"A connection will time out if no packets are sent or received for a period longer than the time specified in the idle_timeout transport parameter (see {{termination}}). However, state in middleboxes might time out earlier than that. Though REQ-5 in {{?RFC4787}} recommends a 2 minute timeout interval, experience shows that sending packets every 15 to 30 seconds is necessary to prevent the majority of middleboxes from losing state for UDP flows."

**Comment by martinthomson** [comment]
That is not intended as guidance, but a caution.  This is something that firmly fits in the application space.  For instance, in HTTP, sending PING frames to keep the connection alive might be appropriate when a request is outstanding, but it shouldn't be used otherwise.

**Comment by mirjak** [comment]
@martinthomson I added a bit of text in PR #41. Can you have a look at it?

**Comment by mirjak** [comment]
Resolved by PR #50
