### ISSUE TITLE
Ports and ALPN

### ISSUE THREAD

**Issue by huitema** [quicwg/ops-drafts#393]
Do we want to say something in the draft about usage of ports vs usage of ALPN? For example, it is possible in theory to have a server listening to both H3 and DoQ on port 443. Should the draft say anything about that?

**Comment by mirjak** [comment]
It does: https://www.ietf.org/archive/id/draft-ietf-quic-applicability-12.html#name-port-selection-and-applicat

**Comment by huitema** [comment]
OK. Not quite what I had in mind but it works.
