### ISSUE TITLE
Caution that there are other protocols that amplify in packets and bytes

### ISSUE THREAD

**Issue by ianswett** [quicwg/ops-drafts#399]
These have the potential of creating infinite loops when used with stateless reset.

One is ISAKMP/IKE, which conveniently does not look like a QUIC packet, but there could be others(ie: Chargegen) that are easily capable of creating infinite loops with stateless resets.

**Comment by mirjak** [comment]
Are you proposing to add additional new text to the applicability statement to address this issue?

**Comment by ianswett** [comment]
I was thinking this would be a change to manageability, because that draft has some text about amplification and DDoS.  I can try to write some text if you'd like?

**Comment by mirjak** [comment]
I guess that's a question for the chairs as the document has already passed WGLC.

**Comment by ianswett** [comment]
Sure, there's always IETF LC.

**Comment by LPardue** [comment]
Seeing a PR will help, we can raise this during AD evaluation

**Comment by mirjak** [comment]
@ianswett are you still planning to provide a PR for this?

**Comment by mirjak** [comment]
@ianswett ?

**Comment by ianswett** [comment]
I wrote a PR, but that's made it clearer that this is not particularly actionable by network operators, and more actionable for server operators, so it may not be appropriate for this draft.

Given that, I'm happy to close this with no action if people would like.

**Comment by LPardue** [comment]
Thanks for the PR. I reviewed it and it doesn't seem like something that could be actionable by the target audience of this document* - network operators. I support closing the issue with no action. 

* this seems like some good practical advice for implementers, let's keep it in the bag for a different document that we might choose to write one day

**Comment by mirjak** [comment]
I guess if at all this would go in the applicability statement instead. However, this advise doesn't actually seems very QUIC-specific to me.

**Comment by ianswett** [comment]
It's QUIC specific in that in the design of stateless reset, we ensured there could not be infinite stateless resets between QUIC servers, but not between QUIC servers and all other things on the internet.

**Comment by LPardue** [comment]
I'd say this is also out of scope for applicability document. I would expect application developers or application mapping writers to consider stateless reset as an opaque transport service. 

An infinite loop is not great but there's nothing special about how an application protocol uses QUIC that might cause the problem Ian has described. Indeed, by the time stateless resets might occur, there is no application context any more. For example, HTTP/3 makes no mention of stateless reset.

**Comment by zaheduzzaman** [comment]
@LPardue  if you expect the "application developers or application mapping writers to consider stateless reset as an opaque transport service", then it fits within the scope of applicability doc. The question here is if we think ,it is  worth giving the application mapped on QUIC a warning about the amplification or not.

**Comment by LPardue** [comment]
My point is that there is no way for server application developers to change how their application works, in order to affect this scenario. So saying something in the applicability draft has little value. It also opens the floodgates to possibly needing to capture other denial of service considerations. I don't think we should be doing that in this document at this time. A separate document seems more appropriate, if it's worth doing.

**Comment by zaheduzzaman** [comment]
I see your point. let's close this issue with no action for now.

**Comment by LPardue** [comment]
Closing with no action
