### ISSUE TITLE
Reference load balancer draft for retry service and give recommendations for address validation token

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#40]
... in the applicability statement? I mean one example mechanism maybe...

**Comment by mirjak** [comment]
Can anybody help with that?

**Comment by martinthomson** [comment]
https://tools.ietf.org/html/rfc5077#section-4

**Comment by ekr** [comment]
The 5077 construction is pretty outdated (it's not even AEAD), unfortunately.

**Comment by britram** [comment]
Let's refer to the adopted load balancing draft from -applicability, once it exists.

**Comment by britram** [comment]
I'll find a stuckee for up-to-date crypto language here at the Zurich interim.

**Comment by britram** [comment]
closing for now, couldn't find any takers.

**Comment by britram** [comment]
...actually, it's in the LB draft. Reference it.

**Comment by mirjak** [comment]
PR #104 proposed to address this issue...
