### ISSUE TITLE
Clarification on allowed encryption schemes

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#406]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-applicability.md?plain=1#L870, this sounds to me that older versions of TLS are still on the card to be picked up, even if that is not the intention here. can we be more explicit about the exclusion here? see the proposal below - 

"A new version could use other encryption schemes than TSL 1.3 or newer and higher versions of TLS than TLS1.3 (older versions of TLS would not be used)"

**Comment by mirjak** [comment]
While I'm sure that the IETF would not want to standardise a version with uses a lower version of TLS, we say nowhere that it is forbidden. I would rather not add anything here in this document.

**Comment by zaheduzzaman** [comment]
hmm, RFC 9001 says : "Clients MUST NOT offer TLS versions older than 1.3. A badly configured TLS implementation could negotiate TLS 1.2". and as the context here is QUIC version. I think we should be very bold to enforce the "MUST NOT".

**Comment by mirjak** [comment]
Yes, we do as the sentence you refer to starts with "A new version [of QUIC]". We don't make any such constraints for other version fo QUIC!

**Comment by mirjak** [comment]
@zaheduzzaman are any further actions needed here or can we close this issue?

**Comment by zaheduzzaman** [comment]
lets close this, even though I would have been happier with stating older version of TLS than 1.3 is not considerable to newer versions of QUIC.
