### ISSUE TITLE
Normative references in Applicablity document

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#407]
I didn't expect any other normative reference than RFC 9000, 9001 in this document. Why are other references needed to be listed in the normative reference? 

The reference list also have duplicate entries  (i.e. same ref named differently) this need to be fixed as well.

**Comment by mirjak** [comment]
I added this to PR #429 - changed TLS1.3 and RFC6335 to informative, so only RFC8999, RFC9000, and RFC9001 should bee normative now.
