### ISSUE TITLE
Interpretation of recommendations need clarification in abstract and/or Introduction

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#408]
As this document does not use normative language and still makes number of recommendations, I think it is best that the abstract and/or introduction of thid document need some text to clarify how the readers should interpret those recommendations 
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L60

**Comment by mirjak** [comment]
What exactly would you propose?

**Comment by zaheduzzaman** [comment]
hmm, the reason for not using normative language would be sufficient I think.

**Comment by mirjak** [comment]
Not sure what to write. There is no requirement that normative language must be used in RFC and moreover this is not a protocol specification. However, these are not something that we should note in the abstract.

**Comment by mirjak** [comment]
Can you make a proposal?

**Comment by zaheduzzaman** [comment]
I would simply expect the reason of not using normative language in this document (I remember there was some discussions on it), perhaps best fit in the introduction section.

**Comment by mirjak** [comment]
There is nothing really specific here. If you look at the other issue they don't say much other than that we only provide recommendation and therefore don't need normative language. I would prefer to not say anything as that could rather give a wrong impression.
