### ISSUE TITLE
Clarify control signal is QUIC protocol control signal

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#409]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L85 , can we be more specific here about the control signal we are talking about is QUIC protocol control signal not really other kind of control signal that the network might have? also here it is compared with TCP, should it also mention TCP with TLS?

**Comment by mirjak** [comment]
I added the term "transport-layer" in PR #431. Does that help. I don't think TLS needs to be mentioned here.
