### ISSUE TITLE
Clarification on troubleshooting and in-network modification is needed in the introduction

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#410]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L88, I am not sure I get what this paragraph is supposed to mean. Number of things -

- first of all it is not clear that integrity protection actually simply the troubleshooting without defining that kind of troubleshooting we are referring to here and who is doing those, even though it is true that now network nodes cannot modify the transport layer information.
- we are making a statement that in-network operations depends on modification of data, what is the data here? payload? header information? both? I think here we can reference to the I-D.ietf-tsvwg-transport-encrypt to setup the background information required to parse the statement correctly.
- I am not sure how a proxy here can support modification of data. Yes, that is my read of this last of the statement. Hence, hence we might want to clarify what is the scope of this collaboration that we are referring to .

**Comment by mirjak** [comment]
addressed by #432
