### ISSUE TITLE
RFC9000 has better figure than what we have here

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#411]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L250 here, I propose to rewrite the first part of the paragraph so that it is easy to read. for example -

Packets in the handshake belong to three separate cryptographic and transport contexts -
 
 - "Initial", which contains observable payload, 
 - "Handshake", which is not observable 
 - "1-RTT", which is not observable

Here we are repeating stuffs from RFC9000 without referring to them but I found the figure in RFC9000 more explanatory. why are we rewriting it here instead of just referring to RFC9000 ?

**Comment by mirjak** [comment]
I think it is important to have a figure in this document as reader of this document are not necessarily willing to read RFC9000. Thus this document should be useful as a stand-alone read.  The figure in this document is meant to be a simplification compared to the one in RFC900 there it is omitting some of the less relevant details, e.g that there is an initial and a handshake packet.

**Comment by britram** [comment]
Also disagree that the diagram in RFC9000 is better for the purposes of this document; would prefer to keep it.

The paragraph is a bit difficult to read, though, reflecting the history of this section more than what we actually want to say. Will propose a reordering/simplification...

**Comment by zaheduzzaman** [comment]
Ok, I think I understand why you want to keep the figure. I actually had to look at the RFC9000 to understand it better. I hope the promised reordering would help here.
