### ISSUE TITLE
something for appllicablity draft instead?

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#415]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L728 I am not sure what does the last sentence supposed to add to the context and see  it is something more important for the applicability part than manageability part.

**Comment by mirjak** [comment]
I already clarified the sentence in PR #433 related to issue #412. Or is this the wrong reference?

**Comment by zaheduzzaman** [comment]
ok, fine with me.
