### ISSUE TITLE
Clarificaton on any transport- and application-layer delay in RTT measurements

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#416]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L753, why are we so specific about TLS crypto operations here, it could be anything like later mentioned (waiting for a response to be send) or simply work load in the endpoints. Overall the inclusion of the transport- and application-layer delay in RTT measurements has been described in different ways without mentioning why one matters more than the others in certain context while pointing to same thing. This need to be fixed.

**Comment by mirjak** [comment]
The section you noted, is about the the handshake. As there is no data during the handshake, the main app-layer delay with be the crypto. Yes, there can always be additional random delays due to processing also on the NIC but these are usually smaller and therefore less relevant. Not sure what kind of change would be needed here.

**Comment by zaheduzzaman** [comment]
it would be good to refer to same events that may cause application-layer delay, rather giving two different examples for the same application-layer delay.

**Comment by mirjak** [comment]
Still not sure what you would like to see here. Can you make a proposal?

**Comment by britram** [comment]
Alternate proposal: remove the example?

**Comment by zaheduzzaman** [comment]
would actually work, but there are examples of application-layer delay in that later section, may be you want to bring that up here and only use one set of potential reasons for application-layer delay for the whole section.
