### ISSUE TITLE
end-of-flow or end-of-connection?

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#418]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L857, in the section 4.2, end-of-flow and end-of-connection both are used in a way that they both point to the same observation event. if these are same then lets stick to only one of them otherwise lets describe in a way that they point to different observation points.

**Comment by britram** [comment]
let's use end-of-flow consistently.
