### ISSUE TITLE
lower timeout experienced by QUIC endpoints

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#419]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L865, where does this data come from? any reference will be great here.

**Comment by britram** [comment]
@ianswett is there something we can cite here?

**Comment by ianswett** [comment]
The best public data I'm aware of is slide 10 of: https://www.ietf.org/proceedings/88/slides/slides-88-tsvarea-10.pdf
