### ISSUE TITLE
right ref to amplification attack description?

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#420]
https://github.com/quicwg/ops-drafts/blob/3893028c41567d89a6f416049cff901ce87a5c21/draft-ietf-quic-manageability.md?plain=1#L929, is this referring to the right section? if yes then can it be made specific to a particular subsection? I noted that RFC9000 describes the potential amplification attack in section 21.3

**Comment by mirjak** [comment]
Yes this should probably be section 8; 21.3 is not relevant here.
