### ISSUE TITLE
Non-adaptive application faking as QUIC flow to avoid UDP traffic blocking or filtering or throtlling.

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#421]
is there a possibility that non-adaptive UDP based application faking as QUIC flow to avoid UDP blocking or throttling? any advice or acknowledge to this issue to inform the network operations?

**Comment by mirjak** [comment]
I guess using QUIC is easer than faking QUIC. Not sure what to say...

**Comment by mirjak** [comment]
@zaheduzzaman can you close this issue?
