### ISSUE TITLE
How does conection migration impacts the per-flow basis flow treatment?

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#422]
Section 4.8 of manageability draft expects that a per-flow basis DSCP and ECMP routing policy is used to ensure same treatment for all the packets belonging to same QUIC connection. I was wondering how does path migration impacts this? As the new path ,potentially via another network, has no idea about QUIC connection insuring all packets belonging to the same QUIC connection get uniform treatment will be difficult. what am I missing here?

**Comment by mirjak** [comment]
During path migration the congestion control is reset and therefore there is no assumption anymore that those packets need to be treated similarly.

**Comment by zaheduzzaman** [comment]
Ok  then packets belonging to same QUIC connection can be treated differently after path migration. I think it would be good to clarify it.

**Comment by mirjak** [comment]
@zaheduzzaman can we close this issue?

**Comment by zaheduzzaman** [comment]
Potentially yes, but would have been better to put a ref. here to the section where this "If there is a path migration event, the 5-tuple changes. The path does need to be QUIC aware and should not use the CID." is discussed. if things are not discussed or referred in one place then one has to infer the same reasoning/conclusion, which I think not always obvious.

**Comment by mirjak** [comment]
Okay, I added another clarifying sentence and a reference to section 3.5 in PR #446
