### ISSUE TITLE
Referecne to fast resumption mechanism

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/ops-drafts#427]
Section 4.7 of the manageability draft needs a reference to the fast resumption mechanism.

**Comment by mirjak** [comment]
this s 0-RTT session resumption as explained early in the doc and respectively referred there to the QUIC spec. Would it help to change "fast resumption" to "0-RTT session resumption"?

**Comment by britram** [comment]
I think so.

**Comment by zaheduzzaman** [comment]
where was in the document 0-RTT session resumption explained? I might have missed it.

**Comment by mirjak** [comment]
He have separate figures for that in the handshake section

**Comment by mirjak** [comment]
However it seems we use the term "0-RTT connection resumption" there so, we should probably do a s/connection/session/ there as well.
