### ISSUE TITLE
IESG Review Lars Eggert: Section 3.1, paragraph 1 - 443 != http

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#479]
>    At the time of writing, two application bindings for QUIC have been
>    published or adopted by the IETF: HTTP/3 [QUIC-HTTP] and DNS over
>    Dedicated QUIC Connections [I-D.ietf-dprive-dnsoquic].  These are
>    both known at the time of writing to have active Internet
>    deployments, so an assumption that all QUIC traffic is HTTP/3 is not
>    valid.  HTTP/3 uses UDP port 443 by convention but various methods
>    can be used to specify alternate port numbers.  Simple assumptions
>    about whether a given flow is using QUIC based upon a UDP port number
>    may therefore not hold; see also Section 5 of [[RFC7605](https://datatracker.ietf.org/doc/rfc7605/)].

AFAIK Microsoft's SMB-over-QUIC also uses 443.

**Comment by mirjak** [comment]
Not sure we explicitly need to add that...?

**Comment by britram** [comment]
It does underscore the point that HTTP/3 != 443, and 443 != HTTP/3. I think it's useful to add.
