### ISSUE TITLE
IESG Review Paul Wouters/Eric Vyncke: cryptographically obfuscate/protected

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#491]
cryptographically obfuscates

An odd term. I see obfuscation to be non-cryptographic and cryptographic transformation to not be as weak as to be seen as obfuscation (but as encryption or secure hashing)

**Comment by mirjak** [comment]
I replied by mail to Paul and explained that the header protection is kind of weak, so cryptographically protected might be too strong. But maybe we can still find a better term...?

**Comment by martinthomson** [comment]
I would say "protects" instead of "obfuscates".  We have an analysis to support this claim (now cited in RFC 9001), we don't need to hedge.  We used to be less certain (we did basically just invent this off the cuff at an interim meeting), but we're far more confident in stronger claims now.
