### ISSUE TITLE
Terminology (comment 14)

### ISSUE THREAD

**Issue by LPardue** [quicwg/ops-drafts#523]
Terminology: We have made the following updates throughout the text. Please let us know if any changes are necessary.

a) The following terms were used inconsistently. We have chosen the latter form:

   four-tuple / 4-tuple
   five-tuple / 5-tuple
   six-tuple / 6-tuple
   application level / application layer
   transport level / transport layer
   Zero RTT / 0-RTT

b) Although the following term was formatted consistently, we have updated it to match other RFCs:

   DiffServ / Diffserv (RFC 7657)

**Comment by britram** [comment]
These replacements are all good IMO.

**Comment by mirjak** [comment]
PR merged
