### ISSUE TITLE
Section 3.8.2 (comment 12)

### ISSUE THREAD

**Issue by LPardue** [quicwg/ops-drafts#536]
[Section 3.8.2](https://www.rfc-editor.org/authors/rfc9312.html#section-3.8.2): In the following, does "QoF" mean "quality of flow"?

Original:

       for example, QoF [TMA-QOF] rejects component RTTs
       significantly higher than RTTs over the history of the flow.

**Comment by mirjak** [comment]
As far as I understand it QoF is a name and not an abbreviation but @britram knows best!

**Comment by britram** [comment]
Yes, QoF is a proper name in this case.

**Comment by britram** [comment]
In the draft email to the RFC editor, closing with no further action.
