### ISSUE TITLE
Further discussion on connection identification at stateful firewalls

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#56]
See [Toma's email](https://mailarchive.ietf.org/arch/msg/quic/ZqPF68ouXg3U0Y2hsvTX0QTLyuk).

**Comment by britram** [comment]
ISTM that this might also be an applicability thing as the "easy" solution involves the firewall to share state with the LB/frontend (with all the scalability impact that entails).

**Comment by mirjak** [comment]
PR #83 add a little more text here. Please provide another PR if you think more text is needed!

**Comment by mirjak** [comment]
PR merged
