### ISSUE TITLE
update -manageability for BKK spin bit consensus

### ISSUE THREAD

**Issue by britram** [quicwg/ops-drafts#58]
Review and update text in -manageability to reflect BKK spin bit consensus:

- single spin bit is in the protocol spec now
- endpoints may opt out (discuss why; this is for any reason, not just proxies as suggested in #55),
- endpoints should probabilistically out out to provide cover for endpoints opting out

**Comment by loganaden** [comment]
I am working on this.

**Comment by britram** [comment]
I'm not sure this fits in the scope of the document: can you say more about what you propose to be in this section? The -manageability document is meant to be an independent user's guide to the wire image, so information on the spin bit here will be more about how to measure it, not additional guidelines on how to generate it and when not to (though such text might belong in -applicability)

Please coordinate with @ihlar, who will also be proposing text on spin measurement to bring over from draft-ietf-quic-spin-exp.

**Comment by mirjak** [comment]
see PR #66

**Comment by britram** [comment]
closed by merge of #66 and #67
