### ISSUE TITLE
Connection migration strategies

### ISSUE THREAD

**Issue by rpaulo** [quicwg/ops-drafts#68]
I think the applicability draft may benefit from exploring connection migration strategies as described in:

- https://tools.ietf.org/html/draft-paulo-quic-migration-00#section-2

**Comment by mirjak** [comment]
Do we also need to say anything about use of 0-byte CID? See quicwg/base-drafts#2441

**Comment by rpaulo** [comment]
The transport draft already says:

>  an endpoint MUST NOT initiate migration if its peer supplies a zero-length connection ID

**Comment by mirjak** [comment]
addressed by PR #80 and one more sentence

**Comment by rpaulo** [comment]
I don’t see any text related to connection migration on that PR.

**Comment by mirjak** [comment]
sorry wrong PR; should be #81 and is already merged
