### ISSUE TITLE
Document how SNI from QUIC handshakes is presented

### ISSUE THREAD

**Issue by ianswett** [quicwg/ops-drafts#75]
SNI is currently mentioned in the Manageability document, but you'd have to read a substantial chunk of the transport and tls drafts to understand how to extract it.

I'd suggest a short section that describes how it's presented on the wire with references to the appropriate sections on transport and tls.

Currently, the section on client Initial says: "The Client Hello datagram exposes version number, source and destination connection IDs, and information in the TLS Client Hello message, including any TLS Server Name Indication (SNI) present, in the clear."

I think saying the SNI is in the clear is a bit misleading to a casual observer.

**Comment by mirjak** [comment]
@ianwett can you maybe provide some text?

**Comment by ianswett** [comment]
It'll likely be a large PR, but yes, I'm happy to.

**Comment by mirjak** [comment]
Thanks!

**Comment by nharper** [comment]
The algorithm for parsing SNI from a QUIC initial packet is specific to v1. (Future versions will change the key; they could also change the algorithm for encrypting/obfuscating initial packets, and could make other changes to the crypto handshake.) Should it be mentioned "this only works for QUICv1" with the re-written SNI bits, or somewhere else to cover more broadly "anything you do that involves decrypting packets protected by initial keys is v1 specific"?

**Comment by igorlord** [comment]
> "anything you do that involves decrypting packets protected by initial keys is v1 specific"?

I think the entire draft can be prefaced by "anything you do that involves using QUIC protocol properties not explicitly specified in Invariant is v1 specific". This applies to the discussion of connection IDs, spin bit, initial keys, etc.

**Comment by mirjak** [comment]
I opened a separate issue for that (#95).

**Comment by martinthomson** [comment]
Note that this needs to recognize the possibility of Encrypted ClientHello.

**Comment by britram** [comment]
It also needs to recognize that connection migration may break assumptions about the stability of SNI information.

**Comment by ianswett** [comment]
And NAT rebinding. And mention CIDs aren't stable, particularly when the path changes.

**Comment by mirjak** [comment]
another reference to potentially integrate: https://www.chromium.org/quic/parse-client-hello

**Comment by martinthomson** [comment]
Having read that document, it would need to be framed to avoid condoning it.  It advocates a strategy that is not compliant with QUIC invariants.  It's very much rooted in 2020, including parsing rules for Google QUIC, so it might not be a good basis for an RFC.
