### ISSUE TITLE
Document the challenges of creating a 'transparent' QUIC MITM

### ISSUE THREAD

**Issue by ianswett** [quicwg/ops-drafts#76]
Feel free to close this if it's out of scope, but creating a proxy that attempts to passively observe QUIC is much more complex and potentially problematic than TLS over TCP.

For example, all major OS's have mature TCP implementations, whereas a MITM would have to pull in its own QUIC implementation.  If it does so, it would be important that's it's both conformant to IETF specifications and have good performance.  This is the full L7 termination case, which is possible, but a lot of work, and we should heavily encourage anyone doing this to use an existing("good") implementation.

A potential MITM option is to attempt to terminate the handshake, but then only observe ApplicationData packets.  However, this could go wrong in many ways, so I believe it should be strongly discouraged.  QUIC is designed as an end-to-end protocol and efforts to change that are likely to end very poorly.

For example, if the length of the CID changes, then the offset of the header changes and a middlebox who doesn't track all CIDs both peers may be unable to decrypt packets.  I'm sure there are more gotchas, particularly with the introduction of extensions.  It may also be worth pointing out that QUIC frames are not TLV, so any frames(ie: extensions) that are not understood cause all other frames to be unparseable.

Thanks to @DavidSchinazi for the specific examples of ways this could fail.

**Comment by mirjak** [comment]
Still trying to figure out what my thinking is her, but it sounds a bit like you propose something like "If you want to implement a QUIC MITM, please terminate the whole connection up to L7 and use an existing library." Note sure that is actually giving quite there right message....

**Comment by britram** [comment]
As a user's guide to the wire image, one of the base assumptions we make is that access to the wire image is read only. We should definitely be more explicit about this. We also need an explicit statement that MITM is out of scope for *this* doc and if you want to, terminate at L7 and congrats, now everything in -transport and -tls (and, realisitically, -http) applies.
