### ISSUE TITLE
recommendations for using ALPN in QUIC mappings

### ISSUE THREAD

**Issue by mirjak** [quicwg/ops-drafts#79]
Both documents provide limited guidance on use of ports, however, there was an open question if the applicability statement should maybe say more and e.g. also talk about ALPN.

**Comment by britram** [comment]
pending consensus on use of ALPN in -transport

**Comment by martinthomson** [comment]
We already have consensus to require ALPN.  Unless you meant to refer to https://github.com/quicwg/base-drafts/issues/3117.  In that case, yes, you might want to explain how this works for HTTP/3 specifically.  That is, the HTTP/3 ALPN refers to QUICv1.  For now.  We have apparently reserved the right to revise that when we define QUICv2.

If you start to explain the controversial aspects of this (does ALPN refer to the layer or the stack as a whole) then you will soon find that you don't have any concrete answers.

**Comment by britram** [comment]
Yep, I meant quicwg/base-drafts#3117.

This document should provide some advice to application mappings other than HTTP on how/whether to use ALPN, but that advice really will depend on the larger discussion of what ALPN means (is is app-only, a stack designator, or something in between). 

Having that discussion in this draft is probably not the right thing to do, so holding this issue open until it converges in TLS/HTTP/QUIC.

**Comment by mirjak** [comment]
Probably it would be good to have a more general section on service discovery and point to the HTTP/3 doc as one example.

**Comment by britram** [comment]
Create a new section in applicability, and reference the -http draft section 3.1 as an example.
