### ISSUE TITLE
Considerations for NATs

### ISSUE THREAD

**Issue by martinduke** [quicwg/ops-drafts#87]
The manageability draft should talk a little bit about NATS for QUIC.

The laziest thing to do is just continue to have NAT mapping be by 4-tuple, as it is today. This is actually fine.

However, someone might attempt to be clever and use the CID as well. For example, client A and client B could share the same serverside address and port and the NAT can initially distinguish between the two because they have different CIDs. This appears to save address space,  but doesn't actually work because the server could switch to a new client connection ID. In this case, the NAT won't be able to determine which client to route to.

**Comment by erickinnear** [comment]
I think it's also worth mentioning that using just the CID only is similarly broken, the fundamental underlying concept here is that subsequent CIDs are exchanged in a manner that the NAT cannot see -- the only time it's okay to use CIDs is if you're colluding with one of the endpoints, as in QUIC LB.

**Comment by larseggert** [comment]
At least recommend to use longer binding lifetimes for identified QUIC connections?

**Comment by mirjak** [comment]
See PR #88

**Comment by britram** [comment]
Fixed in this doc by #88
