### ISSUE TITLE
Advice on network state idle timeouts

### ISSUE THREAD

**Issue by britram** [quicwg/ops-drafts#91]
For discussion: should the manageability draft advise that idle timeouts should be longer for flows inferred/detected to be QUIC flows?

I think the answer here is "it depends": for NATs, yes, state at the edge is not all that scarce anymore. For firewalls? Maybe not so much. Are there other applications to consider here, and is there any generalized advice this document could give?

If so, is there any generalized advice for how long the timeout should be?

**Comment by mirjak** [comment]
PR #103 is an attempt to address this issue but doesn't provide much concrete guidance...
