### ISSUE TITLE
Mention accidental invariants and the calculus of blocking

### ISSUE THREAD

**Issue by britram** [quicwg/ops-drafts#96]
From Spencer on the list:

> Before I read this ^ paragraph, I was planning to ask you whether "blocking QUIC" merited a mention in https://tools.ietf.org/html/draft-ietf-quic-manageability-06, because we are in the awkward position with HTTP/3 that operators will face less blowback blocking HTTP/3-QUIC and forcing a fallback to HTTP/2-TCP than they will face blocking almost any non-HTTP/3 QUIC protocol (with less clearly defined fallbacks) (see: MASQUE). 
> ISTM that at a minimum, the "accidental invariants" might be mentioned in https://tools.ietf.org/html/draft-ietf-quic-manageability-06, which targets operators.

**Comment by mirjak** [comment]
addressed by #98
