### ISSUE TITLE
DDOS mitigation section should reference LB draft for details on retry mechanism

### ISSUE THREAD

**Issue by britram** [quicwg/ops-drafts#97]
As noted in discussion on #94.

**Comment by britram** [comment]
Quoting:

> Looks like https://tools.ietf.org/html/draft-ietf-quic-load-balancers-02#section-5 is an excellent discussion of Retry mechanics. It definitely deserves a reference from this doc.

> The Retry mechanisms described in LB draft are all cooperating boxes, and servers are aware of them.

**Comment by mirjak** [comment]
PR #101
